---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: ceph-objectstore-admin
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  displayName: "Admin S3 user"
  capabilities:
    user: "*"
    bucket: "*"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obsidian-bucket
  namespace: rook-ceph
spec:
  storageClassName: replicated-x3-block-store
  generateBucketName: obsidian-bucket
