apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - secret-github-token.yaml
  - runner.yaml
  - runner-env-secret.yaml
  - runner-devclusterinfra.yaml
  - runner-site.yaml
  - runner-site-env.yaml
  - runnerghcr.yaml
