#ENC[AES256_GCM,data:cimt9ojxEGXrHjxJtlSy3lntberGq48JEgPN,iv:YpOqeaqpcb5HEF2i2SB7pgNEd2IPFMUnrNf5BviyArY=,tag:r65DZgDuvF11NH839xQdZg==,type:comment]
apiVersion: ENC[AES256_GCM,data:J1s=,iv:pkyObKJipSSi3xph47INEFmPJdBq+eBuAGdUTIS4mwc=,tag:fTIpd8MC7XaVMQfjl9Dtzg==,type:str]
kind: ENC[AES256_GCM,data:86GFMumU,iv:jXKWT9YsgwHtgtJ+h0p5meM8zDcvbvciKZFLzYAxXqY=,tag:6/HUBavMQUZzAVBmgJf92g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VDLRIRdkBBd5072IEQ==,iv:shqPATIiMe/EQlbat0vK/pgenCYNFFzwQYbV/bPfrt0=,tag:OvTRp+FCQuONevX/KKB32A==,type:str]
    namespace: ENC[AES256_GCM,data:EBUvSLU7sRZuQfHQaPorML4J1dmN,iv:ClJmb/UK1N+oaB6plNrxcphAor6g/csKrU+KswO7AFk=,tag:lMG1s6kQtbeAQO2z24Qvkg==,type:str]
type: ENC[AES256_GCM,data:DAfG3mK0,iv:ZiR+ha8Y5nk21rAEVfFT8RRSaMNRE2T8yu9w69IZegs=,tag:Nwjzwi52seRS560HB0u2Cw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n/1G8jA=,iv:3GLo8y1y11qYNEVcZoJv9Sfw/+Zzuw8ED8LcnCVhOxw=,tag:FTV/Y88QrBzFQjOn2kTMfg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:y6p2I1kyHAVC,iv:tVNCYbjLgx8kT0zO26QM5S4Mz1nrSUZXXH0cqF0/Smg=,tag:myWObj3rLDGKrY5ZwUvOCQ==,type:str]
    NIX_CACHE_BUCKET: ENC[AES256_GCM,data:NLF4SNnu78gdNmkt,iv:t8/3E9/0zTthO+RoBsPJQNmtrvrzlTPTXPdY8ElkU20=,tag:9v34ALCHJDiST1phBva6Yg==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:GsPQ5oPpPUgSqAkcmrAzWhU=,iv:jV1mL9OGjX7dH45BkrmrdfSUXQct94+IvQkDAAupXHM=,tag:WcEqLiQxS3/vj5JXHOhOHA==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV0VCcVpsMm1Wc1ZDQ2dk
            NXlMQW8xWFhlVG5EbmxPODdqSWtMcHhRYUY0CjEzOC85NjZvbXU2WFN4UlNpUnlD
            b1A2dVh2NU14WUM3U3VxNkN4eGFRcnMKLS0tIDVZNk83RC9WMnVpUDRlQXRPcVRQ
            Y0doeXFLUVMrVGVlN0FzVVphWVdVZWsKwJDI5C0qqk+PGLpS+c58ErfYGdOKO8/Z
            vX1k1Gzo0MMF+eJf4zd1WefkcYrLh1pDX1TMXh/78mzBigYK+j7vjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:51:30Z"
    mac: ENC[AES256_GCM,data:zFAHw9OzZOJ4ue7sKmHnzncvBlpTMx6jRC9NOu+WtVTkHLjzgs/pWw6caHwzUI+dVUQVAGBYGAPIO2FtbpERbx7CAYUzAQnowj3Vc4nQ8xuOS9tedxUTI97izNTTKkT0hupYl51i9fJbfaJ2oOG3FCAqxYb8EAW3B3+3Se0x0s4=,iv:4PcD/s5uNE3aa0zCQwtbTUb+lypOuxajcJ+Td+ogqxQ=,tag:8fcQHOs3JP+c5CffCiTzxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
