# Encrypt after editing: sops --encrypt --in-place secret-github-token.yaml
apiVersion: v1
kind: Secret
metadata:
    name: controller-manager
    namespace: actions-runner-system
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:klL3MYERVkLkCufPZkFiZDFRNixptjf0lNeeF/LjeH1XAfTulpgSMQ==,iv:ZYSD7zJeZLenNwacWQ67YFI6eln4d+v8tOzI5CMasgM=,tag:NF8vLvLE1E2Rl4A5QPFV6Q==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelNYUnF6TEZVSTB5VGNh
            ZE5nMjhvRE5DZXM4enZtSEkzK2VORkVsT3pFCjg2NzVPVmRKbzV2Wnc2cjRPeEEw
            M2JQdGl2bDZCMjFzYU9rRjJrNEVQNmsKLS0tIGYxVTBlb2RWRTlhMWhRK2o1dnRK
            M090NkhhbWUzYzNpNXN6WmxYMkdKWUEK7ANRvWecLXdrwPhx6C6BK+E1psCVowl9
            PLo96X7T1sGY8xOqX21o4ChaQuVp4mJVqj1fY7RjYCYBLn+T72V3wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T05:43:33Z"
    mac: ENC[AES256_GCM,data:CPyBjXsEzUxPON7/AFC3KmsnwXbp0vl8c6MjgosrLZRBj0MJQf1pbHaCavYUl21rzU51uYoFxOTW7ZtjkjuUHs/dRa+t4XTBZjueYQYd3tNh/rHdo4p32/ef+gj8ZuiCCUga0vuOCc0glKmgLvXnAErJrf0oTe0L8ALaSs2qsPA=,iv:jGa2E0ZwewyhmAatFoD+TQBEdujmTYmyH/o/v/7mJpo=,tag:INi7/QMgV80F7eV8WpzUhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
