# Encrypt after editing: sops --encrypt --in-place secret-github-token.yaml
apiVersion: v1
kind: Secret
metadata:
    name: controller-manager
    namespace: actions-runner-system
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:2uuTu4C26F7S4WPIZREhHq6HnzNe5d7ygZ5v6HyeowFwNdCgRvnU8Q==,iv:KkApFikGC+BZqfv6fOb1PVobR4xGB0at5cIowxDDrlk=,tag:YYd7ZKWjHsGLN2JxHWV1hg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelNYUnF6TEZVSTB5VGNh
            ZE5nMjhvRE5DZXM4enZtSEkzK2VORkVsT3pFCjg2NzVPVmRKbzV2Wnc2cjRPeEEw
            M2JQdGl2bDZCMjFzYU9rRjJrNEVQNmsKLS0tIGYxVTBlb2RWRTlhMWhRK2o1dnRK
            M090NkhhbWUzYzNpNXN6WmxYMkdKWUEK7ANRvWecLXdrwPhx6C6BK+E1psCVowl9
            PLo96X7T1sGY8xOqX21o4ChaQuVp4mJVqj1fY7RjYCYBLn+T72V3wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T19:18:58Z"
    mac: ENC[AES256_GCM,data:o+07jgV6PgHJdK4pJz5abMvKEOwg86AO/OSudGNZpsHg7B8xqNC5oWKRWNtem7zexp5HGHFh5vu+iKEaWCicfGk4gc7phr0JwtQ69Xujc9i/u9a2VY6V3CmBAk1RdEioN86V8pxbTdLCWZXupwJUz217R5MjaeB+DOpjdgVeAe0=,iv:ZcLoQR2hRsQoL82U0L1bgMDyv+S8uErLO9su5HpWB+8=,tag:Wyf94g8TXPHF0542wO1vAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
