apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-admin-password
    namespace: rook-ceph
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:dbXL64Tnm6leHw==,iv:pY7N/T/7WoN7NCLvdZKSN9azdro5ga/QG8MgsgIJ1FM=,tag:t3Jy1cM5dwqf7DUg2KIvsg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVXdaczNBUkx1SWg3WDJT
            enF1RVhDbW5BUjlTTVZKb1JMOFl6YVdobG00CjZIMHRyUzJwdlliVDZuSWhQckt5
            RU5PVzVxZFBKM1ZFQmtGKzFueklLcnMKLS0tIDJ5U3B2ajczVUVQblZUOXNLcTMv
            M2VBNklOMkFYc2lLRktkNFN0eDdiMUkKM2bq1lG+t/vrAqykXNpxY4ihtY5AYQJs
            MZioOhVGztqcgKtwyKjH/j/hxVuzbsKGMcbrUQeirZa0VG/l3+PoUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T01:22:25Z"
    mac: ENC[AES256_GCM,data:+1dUiihJGNwMQV9p20ukIG4Drh5PAK+oUu4wc3lLYUZkQnXgUGhAIdrHeSR2sTpuhKbDP10IDOZ9D16KeXVaA9YUnbrADXJ1BD8STvkXkejAlTUyjycSCscH3dC2G1HDSwavWTfxBBH+DYKeJPOHkBW3wKACJei2XO391lG6jJg=,iv:Kgmm5w6ihU9TLz7p/S/zRowvLylmW2JFGfvaiJXvm/I=,tag:6X3CCYDNay0AFHsWRuQLFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
