apiVersion: v1
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:VvQtrjyq,iv:njT/7ddWnX9W/Nb5RYUNA/R+sGS06oIu+5AhQ0BgW6E=,tag:+CtKiczABA0GaNLamSJQmw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:LN/PpdaQ,iv:kJ0/v3Je/PmwJcsFpf2lP/wdEHrlPUdRdDIVvBzuCE8=,tag:9HaMoJjkQ/kDZkFH9LGV/g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:fdAd4B4JhXC7pHS9HmzCO7Vs8rsDIiCxOuRz56m2vHFMKkoWtsqbDGocR4A=,iv:/92QaIVd+fec/FUEKYF5Z0U4lzKs1Rjp9DfTUgfKMe8=,tag:2y1niw0oSvbcytqkD/00CQ==,type:str]
    username: ENC[AES256_GCM,data:ZqVO1JRU,iv:Rx4yY2zjNKo+bI5oARqwUhExz61ae8rjlTtdViYaRk8=,tag:vOGNCE2ge7nWWAz79p+l0A==,type:str]
    password: ENC[AES256_GCM,data:23/BrcINT5U2F8KCTe9Mjiqb0O5OirD9jbOFfzw8pR/jE0mce45so7UqkrQ=,iv:PKKLzbEYjgZ10FLLqSYgnXmIrAhTsbqTQ644wI2HrGg=,tag:BLOuI68poRo1IQ3EyleoUA==,type:str]
kind: Secret
metadata:
    name: immich-postgres-user
    namespace: immich
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd1RjeFBhcFduWmkzT0VL
            VU80Ti9FVmU2bFVxc3ArOFIxZHgrUCtDbDA4CjBHVmlnYjM4dlEyaEphd0RXWVU1
            c3g0eGFISDd6VU1NLzlNTCtFQ0daNkEKLS0tIEppQnd3SFhHZlA3Nit0bG95YTZr
            SDMxVUx6VlJ3dzVvR2x5WDNjQmhOeGMKsLCeoGiKpnzEf6ApPl4d99VbM85uyfbA
            GsR27ee/tRSRSxbdBcfhC86ZbueZaZqa89sQn6w2EOGofx8YnJmSmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:11:23Z"
    mac: ENC[AES256_GCM,data:jJ3i2k57bNpzr9FIJfxDrkuVjpRfdJwVVt1Zr2ENz1Bhm3Q9SVjRUCwl+mNJdvGiAU2T+JsescKldXGpvU9KuacGwO4dY+sLWmEtZT1vLcutuZz8wBcnZsd12ykUiytQSZIG9o0Pbtkus/dq7l268ygb4cZNRnJubNkyXcj3HIg=,iv:RxSeu4CH4FfUQEQRHHKaqK9hR6ni03DLH5wkvlCLkzs=,tag:fE14fIPC1Tq9u/FdZRkFWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
