apiVersion: v1
kind: Secret
metadata:
    name: credentials-sw
    namespace: kube-system
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:cOL3T9NitYvmwmvKyT+APp3vX+/bZ5LNbeKNFHatL+h3v0D1ybNWzLSDEnTtEuKhDAWoavOrocPY9hEc3wzn0l46vNsSjCEINFL1SmJtNNEoAM+Nrg7NZh8kgcsj8P+TMnfsbGl/THiIRPsRZVVDs0am,iv:HMvUp/j4ZbjXRhg4nnM+O2PvTc9a1QMlAvv1+hK/y7I=,tag:hbtVKuLoQP9m4iUM8o9Yjg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZDRrVTNDa2hBSlRSS0tK
            bWFDTFIva1UxaUtDQm5TcFF6dHVKaFBmUmpVCjN0TmQwTm00dFpBY1NKeExMVXhQ
            SjdRNUN0akM5RXo0TldSeXN1Qk9DZ00KLS0tIEg0WG9DY25oTndEZXk4dUs5VTZV
            R1JWWlZOYlZjMzh4akVrV1UvL0dEUHMKuTxuhFVh9o2TMzRC6UO/uqkRUIdQiNZT
            mubmgLgTRTAP/1DLm8lNicw1pd1t+ZOj8ER2S4suyv3MiKWYCkT5tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T01:28:57Z"
    mac: ENC[AES256_GCM,data:n09AzPCYm4TL4hIRhA6DuJiG7EkmNHLipUq7OkXKzwYoY3XdQazDUgBpF9DU0tvuKEqbOZmXiO6WTMggiMhd2NqFEnFwzjXaoCt2MAw8DH3ekhELzr6Ige4psf8hUmyHbVbtXCHHSuYnJT7/cYbGM+SpeHQzNosotATAn/uSJ1Y=,iv:Ge0e+xGFa5uxjktrNEi+Xr6C5SGqtKYgq+2qHXDgBzo=,tag:pykSCKqo3Cp1jJmgmsp8GA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
