apiVersion: ENC[AES256_GCM,data:k1c=,iv:VYE8lh/7/O1sAmdl4Hwhd6tqqvDft2l97YqSynnxEws=,tag:pMtNgoAoCdhlOvlFFF6nNQ==,type:str]
kind: ENC[AES256_GCM,data:V4EaNGXY,iv:XHgPVlR4vo+/w+Lpnihvod9aXRvhKHYPDZ0SEAHF4T8=,tag:UoG9pLxQ7DPB/lsGaEhT2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/9myeHcUYTn6cDsg+w==,iv:izDFWj+zTRQcNd358btx9wfSBNP2upu4Na3PEjylK4Q=,tag:gg5D//zCWiIYCOznyRENdQ==,type:str]
    namespace: ENC[AES256_GCM,data:81mLNHGYFA==,iv:ZUc1pnNm+8BzSDm90HsIyjfAljwBgPHU2PknZ5FynI0=,tag:JT+kwZ0QaZWv5YAU2fYrFA==,type:str]
type: ENC[AES256_GCM,data:v4A5UguM,iv:qT0p1j4ArWf1FcIBNgV6Ar4Y8G0Hv7DtgGsevGANFC4=,tag:KD8qdV7sq0+RbqzWkCMAqg==,type:str]
stringData:
    TZ: ENC[AES256_GCM,data:uq0i,iv:iGJ/w9EpmU3MLdUl18OZuV19o0dntoUsJtSuF+3waWc=,tag:opBi9ul/F1s0z9C+iwtfiA==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:oJSJ00DD,iv:HUP9hZWqm/ruxbGuIrmnCvnELtmcwMROn3bFUCMTz6k=,tag:wnLOU70Oe3RdPk5qo6M82w==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:wMxXe7V0vkdn,iv:1FAYJwUVRhOMmDSvK5h0Te+1WEGa/YT8sw+ZiAnOc5k=,tag:7RGpa8eSwXIck3U4L+vYPg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:i+hnRiiAgCfyEI7guA==,iv:NVZr8a7kUHdSAm2W9WxHqMWkf1ZTrlTUTorlVwNCUtk=,tag:0vPfthVm1XGCH5c2ht1a2A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:FGqskqrK3bdA1El3TRtYl2/G8AFkQnUR2WbCkeKgUdDudROY+bY9NRnVm2s=,iv:MVuKqPxaifK+2j3rFx3WAL4sCXcJonGKvEqlHCV8H7Q=,tag:6DTcX38LeUkfCjTQ3c+lew==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Il72KN3ruz27FTyp6qEYlAOpGUEJchBo7KF4nBCkEpGQFqEbuARORN3V/1w=,iv:WJvRgD5PqYDFz33dI+jiQS1tddq3YbA6koAMJ1molCM=,tag:Rlv1NyIz7AoiAjbWTG7LDg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:mPie2vlHdVJzuPakE8KeQUt0O2+Y0VafHDlfz51St5/DdR9i4ngm8wPdv5Dxwv3WgeWbqoInzAK2Wtv2,iv:m/UkroglCQPq9Xiy8BI+kv2ASMemDfLBZG+lBXE5lIA=,tag:i7Fv01Nc+p991ixClr+h9w==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:+h6aFQ==,iv:5wfjAzSNHHQWHgz8mYfM30WFss59V+Lto9wpP6C0B0k=,tag:yh/LgJQ5l7M+dejzHLOPIw==,type:str]
    HEALTH_TARGET_ADDRESS: ENC[AES256_GCM,data:3RdWdN0FrKK5GOM=,iv:UdtevXHObUw11xzgDlZtKzDbEEFNxUTeK9TtceRmNJY=,tag:1YsiQLk3X6XIvbLpxUNoIQ==,type:str]
    HEALTH_VPN_DURATION_INITIAL: ENC[AES256_GCM,data:8Jho,iv:/aIe6YwxWdn87Nyutz3o1NtO7G9I5HSqhMNVPGSXRZ4=,tag:W2JQ3L0Hg5AKphFiZFJmog==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUlFV0syNzV3aHc3TjB6
            NGlscUVZUE1GSmNtWkc3S0lWbk0wVmlqVUV3Ck1BUmRaVDJJMXU5YlYvalhZdFE4
            RjdXN0twTlp3RjRPTUlLVDNsaE9OQ00KLS0tIElvellGMlQwTnFzZ3VFdml5cDFQ
            UDhwbW1mR1VIczg4ZE9KdkhIV1JsT2MK6tii1bDg0TeaEyMboz5xjY4wg2x4rQlD
            w9Mxz2RbDKurJZv6c6Ror5SEnBCe9JZubKn7BaFWiZ4SuOhV3j4otw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T15:12:07Z"
    mac: ENC[AES256_GCM,data:nRAWKRYPy2QyE/iY8Wuy/+bRd3NnhY5d0Qg6G4RY8fZ2t1JrES2or8nOyI/KW0e51ntOjjVMDVgz8e4rBOdIt1OXJb13pM+7IzAe8zZO9DzDiLTaV8KlXxtl+Q3nSEVVHQ4gjZ0j4IvylQfGwJv4WwzTi6YgWMxvMGoG1ua2lwQ=,iv:RATKYLkggdZWJGFnfabdDfqH0OSTN5vjCJ81nJ2xAAI=,tag:4uCGF6jKkV9B5/wKeaMq0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
