apiVersion: ENC[AES256_GCM,data:Ec4=,iv:lISQmpNy/20pZigUkF8I8KKXg4G73GUzjOmrUxUO7zA=,tag:O/HCfcRZThEy8SQ2cblSQQ==,type:str]
kind: ENC[AES256_GCM,data:2DJxF++F,iv:+fyTUznm4+AO1GrhgYkgEjHJSdeO/bJSdIr1YjQ8ayQ=,tag:76mN1/ybR1Au3T+DB9Zybg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aEDnw14BM9b8JwXWbkh6aI4sag==,iv:ygM7zK+NUHfFbfLBl+KC4LoU5SuKFID1Uvk8FS/Rc88=,tag:L0gadxnlhxrGJIOUz2FRsw==,type:str]
    namespace: ENC[AES256_GCM,data:X5QLrQ5F7mo=,iv:cExLH55sAwz1ULLI3SgpqsCozq0o5Qhiy4Wwpk4T/Tc=,tag:BbXPwH2D/piJtb2orJnK0A==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Wq6eLavPbqV+2TOh3t1KGsH3uTdklfNApalmtMnp1y3nPnhxqarO5/rddF6hKz9LNBBHHoIx1dr+2GpN18B5jRQ=,iv:6IDUNXUF+rgBOXzA8czZBzegZa+CrJXyGCy5emfc8i8=,tag:N9eadnoT/DjpkP3efAsLmw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T3FXQlc1TDFqajEyYkQy
            dGVKNEphSkZLZHc4R1VOYS8zYnBzdktEakZzCkV3YmgwNkhES3ZwN2ZhYTd6UlJG
            eDZPOU1KaExtRnhEZUptZUorSnVWQkEKLS0tIDhzTVdxQUNjVlhBMWZ6NnBXdDN6
            RHNLblo3bE9iMGtjL0M5a2V4K1dwTUUKKfukSlY/etrwyU8wdu8cSmWPvw1HpjV3
            SfY1VQmznSA5py1g2qzTNZoedudMERwFrxxiU89SLonQl+YaIHAK+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T01:57:01Z"
    mac: ENC[AES256_GCM,data:z6fgzN1yYfu/FLuK7X6qu5Litd5jumD3Q3jbjisCwj+yg1D9W0b4TMmBmIosQVzkeBX6CnvqsQkyxJrAqZa8NMm0/jUMfgQ2LEnAP1GG1YKZrNyuD9f1qVSx3LDkXHS5+53LZywuq5X1JCufz1TJdyjYiFsuTAS/g2qI139jHv8=,iv:ot7rKFoqiu7YCrHhJB78xnQ51o0hbjr29Ym6I+6z+oY=,tag:VCdHuKYjHdfrnQsfYComaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
