# Encrypt after editing: sops --encrypt --in-place secret-tunnel.yaml
#
# To create tunnel and get credentials:
#   1. cloudflared tunnel login
#   2. cloudflared tunnel create homelab-k8s
#   3. Copy values from ~/.cloudflared/<tunnel-id>.json
#   4. Add DNS route: cloudflared tunnel route dns homelab-k8s "*.grendel71.net"
#
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:BEXhhOInBFI+kYgWYMfeaZSawXQE45qkQWwX9NOftuNnMhEDEUQxJO3Pb7zfugJffeDS1bzBQCWZhbJN4e24SRzobnS2VSrJ8EbTh6BAYVb8MNhpxlknRGQRfXvfS0uk1fuaq6zHKunqiH5PyJj8Asq46opmcY2tLWg75e0UhluOg+mK0haA4Pt6ZU8rQLnhn2hnw8pSt39S3DMpMfL8FgrKjxwCIReJY/d/okwx/g==,iv:EqbYsvhtxrkbWQakmjMkmLLWNSY90PnK3oxqnM45Jlw=,tag:PnT/Fsjh6rqtXIYMrpFCcA==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRWtaMGhWRXAySW1jVDRL
            dG8xWjYzRE1zblRGcHY5NzRpejdRMTlmUW5zClRWeW1RYUhrQjJiaXRscmM4Rk8r
            cHcrcmMySFdvRUNoMyt3T1ZydFdpRVUKLS0tIFZVTmxXSkJtVENDRzBFeUViY0pv
            Yk1OaWdYS2FJcHhwMGhkaFJ6THBTQUEK65hNrUOLB9d3FFSlSYsffbEHzKkNdJ7t
            0wxKNVOGufDjoLDbSeyPFNRR5JweyakuTSOjKu4upjCP61IJQHX90A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:13:05Z"
    mac: ENC[AES256_GCM,data:LOy8nik80ZPukgXydqlvm/wNIqJBYsNtH8fbVr7ta/fp6BoPCCgkME2/JwnHxKbRnysW75NZFcK2ps2rKv/x+ffZQsfF2NhCdkPCQcJGVlq6vm59hakUwb4t1zOFovLa7bq0o+iTDkJyRmWZZUbCQ4hZHZDnvgjPaGbnWUAoYBQ=,iv:JWM3XYgr3kclSWUHivXniQvgEQ6JOjcco0DqadfzAOk=,tag:uAHVrJXKAplG33sjDYZ9EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
