keys:
  - &homelab age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup

creation_rules:
  - path_regex: (?:^|.*/)secrets/.*\.sops\.(yaml|yml|json)$
    encrypted_regex: '^(ca|crt|key|.*)$'
    age: *homelab
  - path_regex: secret-values\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: *homelab
  - path_regex: secret-.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: *homelab
  - age: *homelab
