---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proxmox.yaml
  - pve2.yaml
  - skipverify.yaml
  - proxmox-httproute.yaml
  - truenas.yaml
  - router.yaml
  - dns.yaml
