---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: router
  namespace: kube-system
spec:
  parentRefs:
    - name: envoy-internal
      namespace: envoy-gateway-system
      sectionName: websecure
  hostnames:
    - router.envoy.grendel71.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: router-backend
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: router-backend
  namespace: kube-system
spec:
  endpoints:
    - ip:
        address: 192.168.1.1
        port: 80
