apiVersion: v1
kind: Secret
metadata:
    name: mautrix-meta-db-secret
    namespace: apps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:OQ/k9ppUP7pRw58=,iv:l+ivlcpEIvCDgqp4k5zuOlBTkpKu8a2vomDDk/MwkzA=,tag:2U4wHYroo8bpas0SOD2Jfg==,type:str]
    password: ENC[AES256_GCM,data:tqlTtq98OkOl0aFHwA8Q7bgRMYgdwcZNcIdkar1iQul0iH3rOL/RCQ==,iv:2SVN9Ak53ZMAMt1t2eJLtHn96UYrom7ynjkMCXCyJUc=,tag:sRy99JlNxWOV9baWTVT5EQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y1hnTWZwb3gwRmVqY0dY
            YzFHNC9oQXc2NXZBUHN4Qzc5Z2pxbFQ1cFFjCndrNGxpU0UvamtxbWhBaW4ySDdD
            MWd2UlJ6ckI3TytnellLNDZkR1hVbEUKLS0tIGpVSXg4dEIzeFlldlZ1OWh0bkdz
            K29wVTU3d09rNzB2TVdBYjJWSFQzZjAKvYX5PmRWVsvjL79SxyNJshmWY/p0Mk+G
            C9Wlo6dMRi+7LqkaTzxKoiExbE7J4PmgGBHj5ErjdMH5KFZJp1+YNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T20:31:28Z"
    mac: ENC[AES256_GCM,data:cbhSNAqPhqQKfeHp68kKwuVLYG3rGndIKMiAlaGzJdD4gIS7Lw553E5U14/66jbGqzBY/4uJQuURGzZdiJcM7SGUcZUiU8ZEARmcnXDSD37RTQ28FKAcF/HaR1hdA5ODLdcqvlBGRX5RoD4DZhoIplFFgk8z/0S2C/JzM6Ixh4E=,iv:gBrKvfvBqDjLvcjCbixvpTr805P25Oams/0zIewNkSQ=,tag:U2UijHBiuzC/M5psBgvl5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
