apiVersion: v1
kind: Secret
metadata:
    name: mautrix-meta-bridge-secret
    namespace: apps
type: Opaque
stringData:
    BRIDGE_APPSERVICE__AS_TOKEN: ENC[AES256_GCM,data:wtsxSBtXHrakX5wF6nyv55bZGDlcgqIfh23cRcsP0wvomoMnf19zquBRonOiGIy8ePXI9h6R1lkpbIUo,iv:49CIbejnMiDz9zorhTDf051XiWidfli2NmgzO2flIOU=,tag:O0YbYJS0KaL3mH462/r35A==,type:str]
    BRIDGE_APPSERVICE__HS_TOKEN: ENC[AES256_GCM,data:y3w0N5VggDRh2Y8DPQsFygRlDwElaCviIGoccB4K4fhK1ApZcUKoA0XisiZl8Vs5lb1pSW8gcD4Wf5Ja,iv:nV4TuJZZwYafoI/768+BBQ6NxVdxKn/eIPb8Bhv0HP8=,tag:pj2HTHLcKxsHU7WY9qypxQ==,type:str]
    BRIDGE_PROVISIONING__SHARED_SECRET: ENC[AES256_GCM,data:A3KLT+5JWp6Yy3Qp62V6sKPL943GDjOCysrlxoIL4pn3vO1imMDhJg==,iv:VRp118O4KMRFMPAktBeR4ur198tp/kjksQOuBIIUKSQ=,tag:31HwXqkOpdnZVPzAzWT28Q==,type:str]
    BRIDGE_ENCRYPTION__PICKLE_KEY: ENC[AES256_GCM,data:w8edAY0FNjSuDd/ISixFZ5cieMJ/+DtPyUu2z79lbpRPZRCt561S8g==,iv:aVcMuyhOzG4tr8BFvAMLOeGQfnHgvgqzd0xRfBTBxSw=,tag:I8+ZaY1f+G9lTS+Q6CI+Vg==,type:str]
    BRIDGE_DATABASE__URI: ENC[AES256_GCM,data:wAjBmQ+eGlGFFKYlsWLWCpzaCQDGzdFSblg9LeMzSu+yAUefoDMpiZ3Tedpd0pnDYMugTdEACcQ7ieiGoc/WDVuof6jAQP3maILa/uWXYoIs93xoUFROeqscrSJv6OXuchZpC6V2eaDyxEMd6bcjkA0g/w==,iv:aFUN/Pl/2iFI38n1azcoR16xYiFJbj8LRPaGu7WUsys=,tag:FeRRwdkd1xBP+7N3UQ1Tlg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z21KV2E4bkcwc09hczAy
            Tm1hdVB4ekdlclYyTS9QWi9leE1nQWlqT0RZCjFBdi9HdXhNbzhvSVQ0aTJZVVha
            Z2YwbDg5ejlTdDNYbVd0NjRUQmhHS3cKLS0tIHBrNmNhTjNmcE52ZFdjbVZIMEFj
            Ti9PZVFFNWZuN3FZRHUycy9GTVRWQzgKhXbs2F7TRK2dQIYhGVLoIzHlKni/Kp3N
            UvfwinoK5duE+aeKQ4+vhjEblz1V8N1zN8UVAWHt9yv5IMWQg0t7rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T20:31:28Z"
    mac: ENC[AES256_GCM,data:pHhqctwf6YUfOgaYiIQ6Kfv4IHquXqHVdHn0G0Ep8JyuAhVrL11p6QVIKzNi/PwJWZINJcJHDtHVQwzffDlZ/JGddfCBq2GbirGGj/yN6TpVCUDgJxt+pxf9F6HiRKrAn3NxZa+v5JF9MJOjkfT3I600slZ+DdTKgAq8cBYcOFI=,iv:glNfG/XIpAvfmDhM7WjqqciRy4BUqqiyKOHldcDwYP8=,tag:0nYuXo8Yk7F36nAyoXzq+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
