---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud-new
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-x3-block-store
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
