apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: nextcloud-new
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:khQzA+wLrnB4,iv:Yq2rIx1pOovedVYXqdSFO2jfmoGKSlgLgD7ihm2oybo=,tag:RrnLoPQLEoeFFXQmosgqew==,type:str]
    password: ENC[AES256_GCM,data:/Ojoeq8vsW/En2wvkdDYV1mfGhGvCzCsmo1ap2oS5e0=,iv:ibrucWpS7H8v1wu73KrBK4yMuNGdhj2iBcGq60HDvyU=,tag:d8ByprNW+3sdqTxSe3uk0Q==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzREhreW80bjJ2YThJYlJN
            RU1JWC8vMkVEUXFBQUl3YlVPUjNaS2lVblNjCm1IR3hXWWFPNDFwd24vT0hhNzlj
            ZXVpR1FsQklnRTRtUlIxLzV6bmdVMGsKLS0tIDRyUUpEVFc2VjJCS05pdHVRa0VD
            eDc5UkVzVTJpdFFvSTIxNGNZcWJVaUkKD2ON3rj2hDjlOnxeL5ltFgmJRvwFKlfn
            o3xbY6pv8S8vavNNDeO+JUQaOIPF06SHKPiGJCS1tgLVLAKLhuyuAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T04:20:51Z"
    mac: ENC[AES256_GCM,data:aq1fXQRlav75XEmdd5ZHum9XZP0QgpJZ3SaZIZdfxya3MzDXVlSG7CKcvvRf/kgII5rcQeSQP3ji5oyzUhL7avteadg8O2Bmxc2pNdLSGBMpC1L9moJF2YXQMDd6C7f/vBFIzGNzx4QWkr1yMfuSpLg+a0vt6akcker1CBm1L1o=,iv:2kohVmPL3LPzPVTfboDObyM0ruqAEY9gniFq5MouL4Y=,tag:1kboh5PlRpZ6pUQnIZHgUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
