apiVersion: ENC[AES256_GCM,data:rwc=,iv:2hroM/6IAM+kk8izg/8iie9/A3J/VT2e4C6u1wz8q1A=,tag:33BNqeVtXnNZlKqX3YotLQ==,type:str]
kind: ENC[AES256_GCM,data:nMgvN0V8,iv:o+eLXfB04802eoLUoiTZsmSjoAipGywdan3na5P/iKI=,tag:vlZuG+C+xmUAM5YdW07XIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2rtjGv4gCIwFkDlUPlVC340xXw==,iv:9x/VBod6xYzj9fCsUo/SBwBHtC0HAbUU1ZIku1kuK2Q=,tag:NKqVc9mx1/lIG/JZWFrikQ==,type:str]
    namespace: ENC[AES256_GCM,data:zrjhwq7FqIwP2OnBVg==,iv:9gA089pC9ocEZv1iplfTlbWZN3bCtlxBmmzRiex27p0=,tag:2fkRB/vpvPj4MTv7AfQ0tg==,type:str]
type: ENC[AES256_GCM,data:V/gnFmZ09ejmE9yGjo1GFwz862hRY6v+,iv:ZR3gkYwm620QiGPAl30r4KXS+qrJHqHKuT1aISgkuu0=,tag:15vIIIlL4FIOt07kG2WCPA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:90bMaZaj3b7J,iv:bzfu5UaEABHFI/KLdSP9y/NQPSlLvyAvDTG/uo98JUE=,tag:mXOYaCTOwdOMocYh43lSNg==,type:str]
    password: ENC[AES256_GCM,data:EwO4LsMIxH7IDA9GJTcwOBmnHL2BRJ9pHALBs/gQirE=,iv:6xdIzgnOho2W+hNbDY2difjgeR3FahHUggK0s+1A2Ic=,tag:aVhHHC9UnOgXyy2u8JVMcQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdHZmR0ZKSXc1TTRHbHBl
            cFd6UU8zcWtRMkt2R2dwMFZPTDkyNkloMkY0CmhTSkRSdDE0L3JvSHZwRFlZT2Z1
            KzZ1U25GS1NhZ3NrNlhxcEN3T0lkQkEKLS0tIFdMWXhBb2hDbGF2M1hQcWtPd2tY
            MFJBNEFvSzEvcWYrYkNXWkNYb1R4VjAKRf7ZkYhK7YMB01HR3fgpVBljluejMNUj
            /GOFBoi36oyZjf48IcBFzHrU07VD3ooxHoNNV7DjM5qzuAmUiMGsXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T18:29:03Z"
    mac: ENC[AES256_GCM,data:cp9skRb183Ek34Q6KmV4trqB6zSA5mKD0zlL3uF78QdNS8DsxJZBwUyt+ootDSm39cXB9FoOkG9M1LkaA7mFEpNfQoycg5S6VNFXDADMBuvLxPH0DdUo4NKn24iuQzkClp7EcMqGyLhklo1UkV/LvSkxHUwVhoRrUe8zt1MANsk=,iv:eXAMoXZs/jJKSSFHDBnCWIW8B2MXZnG+oDSHSs2xNV4=,tag:Sgo1gyYWb/UPfV0OHwAARA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
