apiVersion: ENC[AES256_GCM,data:uGA=,iv:4qaau4ECk9oxckoKHrKlp8D5FcfTbXnBtD2fTw/Xw3Q=,tag:YS4e7Qg2ZtvgnQGtHb9Zpg==,type:str]
kind: ENC[AES256_GCM,data:DcardkJb,iv:RrqAgm2mMnuOS7/ZVwOBgbiQCF7hFtohGXMpj34Byi0=,tag:FWEMAn4poo7OoRMTZ7F7zw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vLtdLfJM61nQ/pjjKEA/6h1/GQ==,iv:x1qfTbVp9qH2ZOGXu1Uzik7cNfwuARog60KR32Q44Oc=,tag:N7dWJEiuC3RlnFLNQ4SkGg==,type:str]
    namespace: ENC[AES256_GCM,data:s0AsT9fDdJO6,iv:D1Ye2CApVF9dHH1t8Dc7fCtFCHht29l63QuVVe5PXgw=,tag:ja/gweNr/mEOYm1uaOfG5Q==,type:str]
type: ENC[AES256_GCM,data:JPxJQupMaWsS4cAXia84e621+Y0ExKbF,iv:OHRcZYMyk0UaPVQK9mWbB4XycGGqXQ/K1e1MhpFXUIk=,tag:Bad561ty3E7vHtCkE72oEw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Dpq5Oxmd6Lw7,iv:yHLqgR4h46EsdK5arRg/T/reALuqJ8RhfwagsG5T1Po=,tag:v5ej0mssrD0MGHah9hrR7w==,type:str]
    password: ENC[AES256_GCM,data:KfEEVGAhUBP73wK1pbysZN+75n+YDOxZWfvV+XRZ/Dtx3wQkZAVeKz5wwyO2aP/WjdU=,iv:LDEyLg+if3b4j1xr83sK86yqZTamY4+LBoOCDnZxz44=,tag:EjOteFpSxStsIL3qYOThTg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVWRUYkdyQ2JBdnpLdWZG
            cTZYWmc4T2RmRDI0NnZVYVFhY0Y1RFgybWdvCnZFTmFBeVBPQWFqTWRYSjY2OTBP
            M1NKbXc2VnFhbFU3TjR2b0MxM2pOTzgKLS0tIC9UQzRSZWpmZ1UrTHFYdVp0NHZ2
            ZVpwbWdhOFRYdHNBbnAvalA2NTI0K1kKbxmsmpNhHRrxZhWZ+g4fKQWOVchAD4go
            2mVnVEaXAZ6ueVKMVWsOdFAaMbfpEZV9L4ZojCzCLIsfP8E/S49sGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T19:07:08Z"
    mac: ENC[AES256_GCM,data:H1zuhzHIhCXDj1D+1maU35/5OzojzDQCRHekVIaQgnoYANUqfaOSFVTTHGuEfa3XJ+QKIhWtZLRT57FMiwXET/3/I/KSv+ZKJx4TRyEJZw/HxtmkvSeZa+mUjqpt3xeR1UWAWKmliWYFIZ2sD6xtJy18TpuESoyduP3dbQaAacw=,iv:+0bCWCFf+gis4xfJGaxwOzLd0kuKP8nuM6htHDCAgII=,tag:PccXiV4Jpa9igFkeJKifsg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
