apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-values
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:8wIDqE72gxxaPGA0J+i+C4MBzSc5GwJmpLHGxGjyO8IueokU+cA6xhg5B2tPTzzJ2lYbul7R3uK8p6H3X+6+9CSqYTqLvTD8ksg7QfMBkLmlLE3u8yCY59mU0VMykE6oxEGAuDmeKdvmNzQd/EiLR/2Ur8hSni8Nh0HDnHx2B+OcCmA1HkMKxdjyS67lADGmDawOmW5hX8HDil5RTz6Qxe9RgHN3c9Mem2gNgnHErrEJ68shrS+EE69coklC3xG0xKU/+IVfG7Hqi7yq9HKImkj/MWYL1DWtn3xJOyMZPy/PyBzrd/V5+0no71du1Ibt9H/0U6mGGzCr4Bm2KKzVCIgQswf0xN7cKk3G2VyOxv09/7juQuKmz2lhUyAzTTU=,iv:0ftEFMUsiorMH6vCxFuO7k8H19ssiF8Kf5jqYRjjo0Q=,tag:Vyw0Chs2kjU055QjlUVI5w==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQck5SdURtNDBHSGFvb2xC
            bjVNU2ZZT2RBTG1XWmlEMmlTdjNxNDF1angwCjIzV0tpd2t5ZFVuZGNPaEtiL09W
            czRmTkppOVpYRm1GdXR1MldoekR0UFkKLS0tIHg5ZjVzZ2xNOFlYcUJ3VzBIOVds
            amhEejBrSzNzRlNnK1VmbjBxZTJqbTgK/FU8emODAmSmYoHxqE40O9N63xt6T4pk
            V5BzvTVL1jGp97rXZLU5cyI1BKU2+S4EzkU7tq8uFw6Ym90+OzjttQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T19:23:21Z"
    mac: ENC[AES256_GCM,data:W2QfJVesAmSkWSioOQye2Q4lXBGFkI7T5jLYKMRuPhUKUvgO4m36Lcq0aj6MnP3RPIwp2fFAHm5fz4ScoVpqNM0AcMIqV+e/ulJu+oQuX4BcUISNg/SxhVy3yTRUP+SYCk/3eFSkVrMa2L9m4KYEyam0/zb1jOsbHOvq+rINyvM=,iv:rnhaOvzvADAYLn4qm24d/RSVdc1gIRWey5rJrU69IC8=,tag:Ox9Wc3YO2KHpPjTk3l9uvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
