apiVersion: v1
kind: Secret
metadata:
    name: bw-portal-secret
    namespace: vaultwarden
stringData:
    CRON_SCHEDULE: ENC[AES256_GCM,data:p/b2HFuMgx9Wcw==,iv:5w+YVolwsKgyC/x21yPEPr/0mggKs0q2Dmn28FPsJN0=,tag:gKGDjIBFN7srNtTFbfrgZw==,type:str]
    TZ: ENC[AES256_GCM,data:cEa/QVGckPdqj8nmEJPNVg==,iv:je5t5+bVj12SA+okoBxVFGFUn/Sh3Gkb4Mm7j8jFsig=,tag:HGMmXWasLwKX3nsBpH2gTg==,type:str]
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:NdmKrt/qo5GFuit+hw==,iv:5orhoZWQWK1JvsJ316QdOL5mWJGJ+gYJWP8531i9C3c=,tag:guRGgetl0tKobD2maveuDA==,type:str]
    SOURCE_ACCOUNT: ENC[AES256_GCM,data:0dHCfCEmYnvGLmsxlR0ba5Z91U26,iv:rrKIUQ04YgPBaXImpnJL+XzJljQqCfGIRyTzpzbmP5g=,tag:vc3RFd6dacrvisbal94kmw==,type:str]
    SOURCE_PASSWORD: ENC[AES256_GCM,data:EC/KqLsRdcfHOm8Kxg==,iv:UrJ53P1F+XdO/frVra9bjRbVW98qgWWm26M/G7BlTSE=,tag:Oo8AoLjWg1v4GkVB6M3Cbw==,type:str]
    SOURCE_CLIENT_ID: ENC[AES256_GCM,data:FYBzJME+kWoFqmnziFgZedKbyom1NMWOmxF9uMGVsY6GYIwOYYQYPVA=,iv:HMljJ2eedpdnHqzEHJhDkl3j+CSVD299fBg0H7wo8yo=,tag:T6/Q5jCblxr2UjoE8cAbuw==,type:str]
    SOURCE_CLIENT_SECRET: ENC[AES256_GCM,data:enZk1eLl+M4xQaBTue6in2jRNvtDZ6eL6ghNoRFO,iv:3e9au2PdqQdM9Qaasc2mxj5aXdM/uMUHh0HNsRf9SVA=,tag:IBN1CF8lPx8jqaCzWzU4sA==,type:str]
    SOURCE_SERVER: ENC[AES256_GCM,data:MR869hKpXCxlNx2h90+glSEiYOhJoyTY5z+sXPg=,iv:1w70is5jOi/cLDj7/PA4AJ4vsLnfkcGfY3C3/q9f8iw=,tag:2JqSrQNlvMC3MDHVilhRHg==,type:str]
    PUID: ENC[AES256_GCM,data:Zg==,iv:tJFH3wygKGqokVjeSiQxrUuv7+EoRXp8MkcPZ4MTqXE=,tag:J4kqcvfXYYn18RTStFBx8g==,type:str]
    PGID: ENC[AES256_GCM,data:Sg==,iv:hH9nwwKlIJOwS/x4uiTYq92V3lr6aFPJ+JOCRKO8uPM=,tag:XQjd75PNosFc5s1hFXc4GA==,type:str]
    ENABLE_PRUNING: ENC[AES256_GCM,data:Bp53dw==,iv:Y7lQ853p9bsKbNhgGlNUbxjC4Epxk/NUyvLT/OXpFMU=,tag:bnHAMpyxJ5NwOspjFC7BDA==,type:str]
    RETENTION_DAYS: ENC[AES256_GCM,data:y7M=,iv:+EG8JHBw2ml/UZ+Vu4qXsPwt/62YHl60KEJAz9dWkhg=,tag:sBvDHycObL2R6ByhIQbJdA==,type:str]
    MIN_FILES: ENC[AES256_GCM,data:cKA=,iv:r3QKwExn0yFCM82e+EaxOfY8VpwZEnXGrRBFIoOcA64=,tag:iseZsdHBiz7QLx1G00u2Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUU5TMk16M3JyVWg0dXpj
            V1h1a3QwZ2ZxdERVRnU4UjVxb2Zvbk5SL1RBCjBRVDRpQk0vYWFWWHhkcWRobUM0
            RHBoWWNJc0tocEoxQmRJOG9yYmpSQVEKLS0tIHNJeXdDR3JzaitRSjA4UG9SUE5r
            UUFRRVIvVVg5dnNQZ09aK3NRWXIzMjQKYZEjfW4s483wPDmZ3E82t/eSfP5Dicv+
            kxka35EHmqtZkH3nwGO5Q1gVRDb5VDlXz5HI0vIi8M0K9Yt4bfnpsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T19:25:07Z"
    mac: ENC[AES256_GCM,data:s68jPi997n0I+D2pScxI3YcdoV9YABiLoaiSe/pb+Iv4qcx+0WyvekmSBCdz2Es9yW1aMwWWh0POKmi6raRB/BLHLPsIoImMEnw8zyxCRRAeD2Vg7WDJvJwQy1VKHfyhvb4RXtxU8m5H0mk/aRPU152svrKRHbJfy4iV8VcNohs=,iv:bjmHVXbecHfzabgzlBykZBfXeKmmm+Vypjgihbr59iA=,tag:f60Akyb2k/gTSVALbNXofA==,type:str]
    version: 3.13.1
