apiVersion: ENC[AES256_GCM,data:1+8=,iv:5WDLz8REYYiS5m/QyjtJOkn7D8WP8O0WumI6FKLHYwQ=,tag:bj8gU4atXQcAv31KqXE7tA==,type:str]
kind: ENC[AES256_GCM,data:F7Uqee8m,iv:vxmdUWU2/MbppL/Mevlj+gQx+xDQUf/AC28r/d2VDLc=,tag:8K25i89PVFXSRnXySdguMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data://+mKbDcLrC30nVL1tgbrJaW,iv:Y5ypKFpMNQqaAGDjLsPqPyHpL3GYtXAd9gftj+jUaiE=,tag:QgZPrkzKqZw8L3RwJaI48Q==,type:str]
    namespace: ENC[AES256_GCM,data:+aTYqnnYpVA=,iv:bfnSeteFFaGOdVEb7JI+2Ibh5YuVcjkmhPaDBXFAf7U=,tag:ekHVEKgLpo+ZP5bDL8p0PQ==,type:str]
type: ENC[AES256_GCM,data:gblJcngi,iv:YVxrUsZw5CG4lOycStxdYcDGG/hVnjm8/8Wf0bBlL04=,tag:4NYEq+IRxv04AMorywVJug==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:yIW9QtjIbej6yV0pmSYYnmsNBkw=,iv:cjo8NKbUvKhGj0zjcUmTMfRrKN5z/vr+6AvNc2fEOF8=,tag:Xlk9IrxlXNvKIhZclAmwzQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:XyFisIPUwl3e,iv:LrNt2No7udmviybpQH/ZVASBbiKskaCIFxYZPjIwT0E=,tag:0ApyhjujtLj8hjGzg25wdQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:ft4N8Q==,iv:L9sAdVk6CyfZS5irnt7StR2aGAWCNT1HAAhwJj+gwso=,tag:MdREe/3rMuhBot0gmeb6YA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:L8q5LWj7uPHc8ILABw9ddmdhLDA=,iv:fdhTV33vx0QLz4irwqqQxapxSFIrH6tuBbN7Flv3NS0=,tag:YzN4n73981nayoUkaM+j6Q==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb0QraTJkTDk3aGtlUjZk
            eW1xVDJzZWljN1l5L1ArT2lsa0htNnNtQVhrCnR4UUdnTHdFMjRxcUpSRkJ4L29v
            UmhJOE9DQ2xPaXMyZ1Q5RXEwczBHVTQKLS0tIEZreTV2OFlEQ2x5RGNONzJ5VEls
            V1JKTXFvaHNac2kyU3NqWlhucENLalEKikITfARTTXj11XKG5oNAO1xtFD2P85dw
            gL8O+LVC9NaW9PVssvN4/g/d6c21394VtFwnX+NNpXyyg9WEAOaT6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T04:55:39Z"
    mac: ENC[AES256_GCM,data:HIW7ycCxRxMh1oQmrvl11FGBVfITZidn90+GRQL48oULOeIC/vJxrlblEefIsZzXdT5O3amqTqDl/R+7kKSQbLu5du14XkM4t0553vk5g0Bw35evSRf0iJO9DFEoYJ+MlYCF7Q7SHD0o56RgwjgINifMfPi26e/yTKAUcdsTN48=,iv:i2OeGoASlwbhqw65GCQL2BZhTLBIDFDymIBafk5xaDw=,tag:Kb9BwqKySUZuEHVzdalpUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:9n8=,iv:Z2a8ERrw2hGPNJ3M5NsI6y3FsaJWswSF2jT+nKi/9T0=,tag:5NxyRxX8bvxStefmHs5SUA==,type:str]
kind: ENC[AES256_GCM,data:bDqaYjKB,iv:LA6UwyCKqmIaE/Wp1Ejyg3WVwcQYwMEITwc1JIbGjE0=,tag:GiI2cu8oMCine+nc65unlA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nv5eyG2f8P+Vkb+W0Qxj,iv:GxIS1rL3ou/C9GV0JkpkJCoQwieZOulAuflV6dxMVHQ=,tag:dXCgGOwilAjs8ab5zhNtwg==,type:str]
    namespace: ENC[AES256_GCM,data:bI1sg2PlGhQ=,iv:boTPUYjwxjiHCYhWOfKjYUcv+GCMIsM6cHRO7/Pa0hY=,tag:CwdCY1H/9PCkK9CAjsCeXw==,type:str]
type: ENC[AES256_GCM,data:z/boyRnc,iv:JZCUCoOXv1XMnrSxF0ipyYHsr/WbKRPinSfVijo46QY=,tag:Pp09hXG1IubW7nQe2LIJ1w==,type:str]
stringData:
    secretKey: ENC[AES256_GCM,data:ezVgER8+UqDUSIQ15uutWNiKVs6F+0LXJN4pxqy3n08olnNIP+kl5lGnM6tZyU+Y/v5VUv1Mgd1B+L7I2t6b9A==,iv:fhh4EmLgJZNNaL9InleagrbYR+PTArOi27M3pqZQfas=,tag:OQzq2WLJrmRcJAtHNV1l8w==,type:str]
    upgradeKey: ENC[AES256_GCM,data:gpCXlNKGQlZQCIyshGJYFw==,iv:gP9FW9Cx/YLYzo5gWWeiEd7joepGzE8mfUMsyac4sHM=,tag:fyPpabVGwgaV37OIzRZ2zA==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb0QraTJkTDk3aGtlUjZk
            eW1xVDJzZWljN1l5L1ArT2lsa0htNnNtQVhrCnR4UUdnTHdFMjRxcUpSRkJ4L29v
            UmhJOE9DQ2xPaXMyZ1Q5RXEwczBHVTQKLS0tIEZreTV2OFlEQ2x5RGNONzJ5VEls
            V1JKTXFvaHNac2kyU3NqWlhucENLalEKikITfARTTXj11XKG5oNAO1xtFD2P85dw
            gL8O+LVC9NaW9PVssvN4/g/d6c21394VtFwnX+NNpXyyg9WEAOaT6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T04:55:39Z"
    mac: ENC[AES256_GCM,data:HIW7ycCxRxMh1oQmrvl11FGBVfITZidn90+GRQL48oULOeIC/vJxrlblEefIsZzXdT5O3amqTqDl/R+7kKSQbLu5du14XkM4t0553vk5g0Bw35evSRf0iJO9DFEoYJ+MlYCF7Q7SHD0o56RgwjgINifMfPi26e/yTKAUcdsTN48=,iv:i2OeGoASlwbhqw65GCQL2BZhTLBIDFDymIBafk5xaDw=,tag:Kb9BwqKySUZuEHVzdalpUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
