apiVersion: v1
kind: Secret
metadata:
    name: lazywarden-secret-env
    namespace: vaultwarden
stringData:
    #ENC[AES256_GCM,data:70dZRVXjTv+ipf7HjWq41+AZVkrUnLf5o4SbF37bSAvFDL1AyGNVa611rnsSOg==,iv:rzA5fl9DfK5OyhGh7/P9aww6xkJIsjfDwQEE8pbjprw=,tag:3t36BAXxAQBN9p/ju2FZdA==,type:comment]
    BW_URL: ENC[AES256_GCM,data:vZt9ejqurs7vRjzTRLLAisoS+2CV4Vf+1UvJiEm4N9ydw5ro,iv:7/mRY1EWwWsmlMso/LAz2/AI8FsBzKpJRRUsR9EqrA0=,tag:qlMS1Tzri9934AdzTriiAw==,type:str]
    BW_USERNAME: ENC[AES256_GCM,data:+9fL7NjoHGYhzd7Pr8pNtQz/6fG/Mf1EX8/dY1oQZIIkK0Vg,iv:9x3LbDHpx0kcrdjCuLCetm5XxK0Wr3j7ILwbjIjC60w=,tag:O8TnXodvn5XAbnI74nHw8g==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:5kS57yRnmvhq3tKT+se6PUXERt0XotlvDqBW54vLnwdIKeiy,iv:kHpgVRPFEXgHEQ2gvuf7Fl44/o0SH+xLkg7ZbdU1mXI=,tag:dLY4PRtzuXSHTVkIiDOf+w==,type:str]
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:B11LqaYw786riUY4NGB0+ReXAIa+v/JULOU7Jm5XDW8e01A2,iv:q7JtgnM5RRXZTnjRlpTPui1gjimj5TQw03i9uw0ilTI=,tag:iVDqTH8FgquF5XqYu+6wqA==,type:str]
    ZIP_PASSWORD: ENC[AES256_GCM,data:sL8/QLUUsrUqtNXuKS6PxBQqW4w0oTgqVfQBGN32v5IV9eDw,iv:XZ9NQsFvnJouLvD1rXY7v2HXRwLYSoDVnDkQmZ5DiJg=,tag:tQXToij3E/NhyQ4wRc9ZAQ==,type:str]
    ZIP_ATTACHMENT_PASSWORD: ENC[AES256_GCM,data:/zNyWWQBXApuGIsXxL8Ehjsy4GDW+BmW8Xh5eVamuaTcAtlE,iv:V+86YCjXbOxcXfk2RtS9feV/j30diMo6A80853MeCZ4=,tag:4rwUigPs/jTg3zBAL2UAAw==,type:str]
    #ENC[AES256_GCM,data:9niDYAvCZKYZBmvYBhrqdAvxLeYggaHF,iv:N+5f95lyqETQ61b4qMaBNi1yx3TRoz+Du7L1CrvPwZ4=,tag:5JiZgdrEsdzt9jdzKNtn5g==,type:comment]
    BACKUP_DIR: ENC[AES256_GCM,data:MnxB1Jg6wddI4V7njHxd/1ByHWkVXrr+C+s2kPqM,iv:Tgi/hNT0VySxoFVD9mqSXsJiUMZAM4vhuOwweuON3rg=,tag:X06EFLOiT7pdSf6aGCqgUA==,type:str]
    CRON_SCHEDULE: ENC[AES256_GCM,data:7Wyj/GnjS7b7Kw==,iv:Iv0BhW/oPf3QG42KlcmV9HiFpUmGx5EcEIhOsS5rWg0=,tag:vH5E/2mUbgC2fZ8yBi431w==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:P+/2VKOZOnUF04JLz75Z0g==,iv:7kPaReXSQTPmFW2875kIJbJAQV85oBp4I0XzNphQQ5U=,tag:So9/j18Sb84TTNE0H6KwPQ==,type:str]
    TIMESTAMP: ENC[AES256_GCM,data:bvILad7z4cjLMCdbmObJ8NCyUA==,iv:bFeA3JHV5cTd9DXH8/YatBhhXJ7gHewthcZbzBDt/qc=,tag:hBhh3eMT49uz2x1H5/zLTQ==,type:str]
    #ENC[AES256_GCM,data:bSy60+SfkFgAqjxhUz0mIozs7a4ugg==,iv:CJopfBeuuYNHTV90dDlptnYqRjKpD8qYPooNtHqLa5Y=,tag:ON7de55jrFMjDGfgAcpPOg==,type:comment]
    API_URL: ENC[AES256_GCM,data:7+YGVuAQga/87kh9ZY6cdRFnrEzgwbK3nGI0dksGzPTA,iv:Gv6bziiIwlAdGRPGAtmMjHOMUBi+gwH/CGaTChpd3xM=,tag:VsRF3B6SchNDp4C6OvA1sQ==,type:str]
    IDENTITY_URL: ENC[AES256_GCM,data:RPcrlJfBOD15j2kVVlF8SBxMdJ26JMudDyYvdQycukGeeOXQ1tw=,iv:5jD3KXI1d1QTzQZ9/P65VxuCufIDvl9lppy/58+vPoU=,tag:jAfVwXwOf25Ev5OM8hucmQ==,type:str]
    ORGANIZATION_ID: ""
    ACCESS_TOKEN: ENC[AES256_GCM,data:X8lnH8lUN8sUFQAwC/mqQdw2OUbGVXaWCqiFsARsCLPJZTEHMMy8NSg1myc7wqC9+N+CPKKHLE1E8lNyUiyqFWW00iFx/m5t1w9ZqcmasZKA1PpjvuuwaGb1L86xL8fT/1O0ltWPAmf+l7p5pvidZXkHvSKJEIvDIDfU8pEdj7NO5GM0ElzffK/7tmqrcyp3oOrKrPBA8dVUKtRrPVwTUG2ISYpZqaAiYphEZdQOfd3lQaPD90W1oigSSXkvcxbUc/JDX+pSfe7hJQtg0YnCCKvQBb1iiFZuEd2lhBNVRxxe6pnNP/tSNqB33M094CjocZCzpwYNcBlOwlTkL8v+yT2gmr+uJtFt91wzlj3e9LKDv5Vwt0LF6gBkVUZTdmqJV+7aIXzQv5X8W/8yzcxWof2uL9pKkI7P0di1wz71qfUmh+Kuhz/FOAzq7+QQ+TMoG6WQEe2o0UZ1a81YmUp+QgB7hPLMG6fRPmHiw/sSTjBH8Z+TPO/yMOnFX3g6r1oGj48kLSWeEkJrmgxEhp+uFX3XjJQG8OtWNARflHZ5TSl8k9pLCpZFizufcCcKG/drR09XUQT62qa6g1Ekkr4g+zm5KtNOmJlmkaEPEny8Vm5g0T+VHKJh5OGqAUX8uyrYQ4EGnXMoQGBJX4ApJIgpNACjKdMhBYS/ttxgk3x/FoVqry3fQQrF+kGPuewcy56if3YJa6gsvSX/oV/tEpiX0q8sGExqd//WbFdrx8N4XShz0lOJCyTJzKTaU4gRpcnDiDwpawoNkBP7Po3OXJ+3oCrkn2EjjXQgtDgYEsVk2zVKwYyn7qhb30G34FLKWlWEGy9Nu+FFQpzs4gXzTg5/M+2fEwq7fGp6tz34cI+6SXZeRZ7VIr8rZ72gZZBPZoJj7UHaJcoE8u4UgTn/FM8JuCVCE1vlcrcDBcGrmHFO2lVbjiSGB3gXUmHIehoXBYEWLYVw2QNUNxWMafx141jB9CPVoAFPLRLWLP5l7XCp3x14+Efadh/3lcOtZNfQfh02pSG0KYNTzTcWldGDA9L3+Pyh7GJP5emH4OfunCm6DvaVHOYGvhROq54yLUTFAEdRZx0hBusdTXZRMG0HNC0fudUsOoKzUPEmo4B1kt3wnrQp580UCq55IaTjnp7JUE36eMwGJQG10jXzUCBxzz4GIgVRztjZtfcsFdMA2iiXA3nHGnJDroBD2hOduLT2tA08uzn/1CsWIGmDcULO7u5DRcP4VJxUeqR+rTRun85HiV4SXCAcpos=,iv:LsFeKU3d2nbxS2PABGboBra5/WLADi8HkWwyE8/NFB4=,tag:Gxym2Z856Awc+N6ux67cRA==,type:str]
    #ENC[AES256_GCM,data:2MAWNitw1mTcc5NLpZR1H7z4tCIJCaQqygW8NVHGtkE=,iv:5OWetuV+GZXbP9KVKQXapi1jTUFrRGTl3YPAlyOiUvI=,tag:urczWyth1vTba0z854QDWw==,type:comment]
    GOOGLE_SERVICE_ACCOUNT_FILE: ""
    GOOGLE_FOLDER_ID: ""
    #ENC[AES256_GCM,data:hU75o9dGeR/Z6bO8YA==,iv:FtNkOQghYGHQDpNGU5HKlAJfR0XgyhZ4C6PkntQiYt4=,tag:Zgs5PB0xzl9udjszdOkGdA==,type:comment]
    SMTP_SERVER: ENC[AES256_GCM,data:eS/1dL2BfLHFN3X4ymOmxQ==,iv:JE67pI8bxjmU19tyIEUOPqwBOD4diG7shXS3KPFfAhA=,tag:4qUW2Ebp7NTsPT8fDBXyCQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:w8frbg==,iv:RiCEmQGS9YSimokYrtrEk2Qpk42mxgeCp50+cZi1qwI=,tag:Pg1yB94RtgfVkU198uGgfA==,type:str]
    SMTP_USERNAME: ""
    SMTP_PASSWORD: ""
    EMAIL_RECIPIENT: ""
    SENDER_EMAIL: ""
    #ENC[AES256_GCM,data:vAKfVk1cOh0bRlXC0g4usFdrkHgDfyus916ylvx6869Yvsenm9NUK1qpYLBTU14yHtTMH+h/e8pklg==,iv:ClaHgODDXRwi3NhPhwnqLkrW6oP7fZi9DykfwY7GHhU=,tag:XxJvOZPkwBwrYQ/vvaznJg==,type:comment]
    BW_TOTP_SECRET: ""
    PCLOUD_USERNAME: ""
    PCLOUD_PASSWORD: ""
    MEGA_EMAIL: ""
    MEGA_PASSWORD: ""
    DROPBOX_ACCESS_TOKEN: ""
    DROPBOX_REFRESH_TOKEN: ""
    DROPBOX_APP_KEY: ""
    DROPBOX_APP_SECRET: ""
    TODOIST_TOKEN: ""
    CALDAV_URL: ""
    CALDAV_USERNAME: ""
    CALDAV_PASSWORD: ""
    NEXTCLOUD_URL: ""
    NEXTCLOUD_USERNAME: ""
    NEXTCLOUD_PASSWORD: ""
    SEAFILE_SERVER_URL: ""
    SEAFILE_USERNAME: ""
    SEAFILE_PASSWORD: ""
    FILEBASE_ACCESS_KEY: ""
    FILEBASE_SECRET_KEY: ""
    KEEPASS_PASSWORD: ""
    STORJ_ACCESS_KEY: ""
    STORJ_SECRET_KEY: ""
    STORJ_ENDPOINT: ""
    R2_ACCESS_KEY_ID: ""
    R2_SECRET_ACCESS_KEY: ""
    R2_ENDPOINT_URL: ""
    VIKUNJA_API_TOKEN: ""
    VIKUNJA_URL: ""
    B2_APP_KEY_ID: ""
    B2_APP_KEY: ""
    #ENC[AES256_GCM,data:pZUxB+PaFqq+IGiTbBc1oTEAMpWOCQ==,iv:nqtXh8TBTyOgggS9hB1WHIuasa/VFSf0TD0RN1kcbH0=,tag:acbO5FreTPgGt9rtoArLeg==,type:comment]
    TELEGRAM_TOKEN: ""
    TELEGRAM_CHAT_ID: ""
    DISCORD_WEBHOOK_URL: ""
    SLACK_WEBHOOK_URL: ""
    NTFY_URL: ""
    #ENC[AES256_GCM,data:quBpciRLh9aIX4NpmvS7P0Jnhd1UftFz8aef+AAV9NuW/c5zaG5N4xlXIqRjvdsnkzhAY4E=,iv:f3BCR06IwiCpnO3GOKJA+uB9bBqnmS0zDZMhMfHd1O4=,tag:/bzgB8y/0gnDAakidPunVw==,type:comment]
    dotenv: ENC[AES256_GCM,data:aIogI5WcrN3BNRwKM71lYuuhdW8yEl2z+W0RsLOB7mbOGUsvCdLVdka7awQhhGwK/RUdiOtKdWb6l/6WbWys93WO1JikSp8SeN6y709AUGAh5tggJXN90ccVYH/l5gu0bDFgFRO6d294H5D3c6Dkfz1MGNZbeLU9M9i/cNBg1e8wQF3nvzkTxfPlJ/0rc2/jSD2ThNb6cKWgt8SwN+nPexdu0orEIP2SJMZ0LG6ocTnKlR8vjas01Y/cUpX+RxRDKzPXV9gC0dYMMBv40n41IA9pMlDZMl2wztXZLcKKg2IEz9SKQwPGCnJABa2rB3/g/xo+diM+DOgK01Mr1eWzmWMjxw80sO/Ey8T5Xa78eU1jrUmP8lrn0uOZQ1Qi9MH3fm9miTlkSzLlVWI1PjaYi73AIW7IstQ9yZ3MPiL5a3zojawKDXHVHAehhtL9LcA208L+Pe6ATpYlMwe2JEWj+F1f43aS5PMdnPQKrc2Gmhz6ks1B4Cs4jIPCx03in4+couEztIS6B2Q14z49j8fnkAn923Wy9qGA4z2zSjeKW/JQjztz62ld17xd7jyYVbRUK7jDiH+wFOFOKUXpI9AjWZiABPf2i7OUpVD/GpVGbvSeAHmIOKGDxCDhc53SrapxAbxYJKCISvHmJfeIehHNnIsXm9aa/lkOS8ouRK8/f41NwURiy3/Ca0UtXXgcqBdbH/v9LIeKMYkEl90U+P1n3F23xT4dn/nv6SbmAgKoC9tiKP6UIgCmzN1N/WiK2z72uTO7MFFWUKx0b8zx2yROxJtgn+azzlBp/V9WbdP1+u+qRWf/UBS+PF9dNAN0Ahsusuu34+7YXn+kVwHWWsbsll5NfeurpTy3qsZ9XZE8Um0RLj0kxrDcrYbogCJUq2Z4Lf96N2X9JUAl75z1X9Fa0xx8guDqeSpc+4F4MNq12cW5BuZJBrdlciO64MiHXU3UUlLE1oAY91B3RoPb9p+PVv7TEZxFH2rot51lc3VTAM18iDfOJiD/Q2yq66QUa1HYer3eU7ljzcvZ/HdFiNZ9HPKvM2GJ1muitMctuMmoQvJA2cJ+1KOYmWxwh275Fjaw2MeQ95Qc4F1UTdl2oubs4ilL/YOoSdEUFl++UPwWCQOSxm9SDKxuaLpNO2kqMtsDfB14XMIiHmwjkO8H791SGX7LDGI3DQr1O6wvBFGkg0dgVBUTkV67aC1LEaHr5xdkSxqODSsLgLTi7NcMq53KFPC9ox06Rj4jpYkCxFk2YmXHe7q64MBb9xF8mVPS+cqDrAB9mmgMOHZMNptbsqnCaMdEnVTewlNSIubjMr3eTSlOGi7QRJsP8rc5Yf/jrUCptGovn+sfAsUsrSmkk9cUR1pzRKWvOWUXhVjqvmAmwF2bURS0gEik/GrwNtD9LkpDFUlujEdRXCljgkXGt75TK/JAe2I5htU47RVUvpm0vnvXfP8Ep6HuI/41A9tCwf7lSZvu8H0++k/RL5lXWK/P0ecS2cClVxNHZrJQbpZ7WlYzXQMUIxE+LaL+4w7ZLTHfEJY1aa6onkQ1s9pMyzwIbCLIw+k0WhoKUAzbiDaFGiX3JaYcKH8goeQ9k4JDdodMzxklW/rq/BPDzvak4o/Ks2YsAz9bBgZ5/zmt0Obu80S7uwplq0f3iEZ/i8EUR2Fy7m2vbbF/aNyyDeBhh7MZ/wrIfBx22C41QC6cbxdNH/fpUb7O11/UrhLniTCxhiqh+W1bD7EwvbUU3j1WT30xaPi/bilKYqiq6toKvLKt73akr/rrG7T1gxLugIfnLxJePQJGNPlOwlyETZnMdUvuVxNRPdH0vu5UR39X6iI+TGIXuGzMqIrsTeMlJ990lJdTzJvFKxL4m7IiS2DPiyvRSG0QcJz0XSGImxPvyC/mj3VtlzX9mYGHzE7CHRm3h+bwrXotP/554AxoxCk3tovmpTHfi2K+9CuwbWFEh/3wb+giFbJS9RwKGngza0iM0+miCg1vTbtvkSLyBamFTR/kEU2FkidR/hqngXGXIK0po9O00LYo02e4Zuouxa59LWG+6Zng8/0JTQcvIHauwtS/q+0v305NLQApEiqoalyr1bM3QbeuaIhopA29CG8NQs/BDYrbOsd7xXSsEI87vx60sZSrgvSJLXSRIkW0QqQkY6aOU8KyKGlz5pK1Grecx0KNVe/ALvfxMLID3hw2afkJ8rsri0EE7bawAEe+uBIuksUCVsB8brRTsqsWWI0Etd765/hqUajGr++Be4CFYX07far0nyaBg/yL6BQWVSWg/RntX3kzbZbQSorUPFIQ1ziBr+5WVflZf1omIqw+Utzf/vQld7nQ4C7o0ygWKFMQEpLwsaJp+u6BSD+RDqypOku99fR+iM3WgFl9veA9c29YsQEp2HXzTztwIiS/GoZgPasYv7YQDmXWwiX/hVWTI1lTqZBfjyCcW9HxFfvwzp7ALisddsb//whhvtrNu5wilSFDHjb0RaRCW0DKbhBxF+S9sx6r3zEQZq4TzDwDHYWIz7SEejWXEIlALvlmUUDLcmPdf3qkX9lx45M9pIsCVeX4lP/FFj6LG+95LN4OCo5rQbUzOcDDzLQ8udqGDl8OQRFwFLaP43byqd85DsFAWexuKGyw871Y42ZrUXwAhyeA3aiPNfDQPfMBvnIV/ZTL8GMMttIkA8DCyNK1kGczUoeq8pidTxTC3/vq9TDkaUpSUj3hlgcmd+pNaUmfzkHx5lv6xVI4I/qS3OEjHZ9moXqcrCXxVJuyhZtpSW6p0+DV7piAJOUlXrBlZKKAAuUPn/jCuwPGPy/8mM3wT2lpwXu+Sgn3oB8uWvcOzkpAV8peTKU0RN0etHxGOdz4fXqBFPvZlYJxOTOVAFT+t0mfaC2mn6lj4Th4txocMjSkwoVnSiBT/MMaUW/fbZMiRTYP+yjIvEqMoIlzGd0obuR8bWLkiTSyxyz2UMLYNTm3pbjoCq+kDdg1ls6CRCAWIOE90Fy70Lg4Orakwpb6B3DV4XWyVrYtXCCyJpinzp4pnwvDjg+0KjI2FXkJWMVNITgPFY+Q1qeulBQmtRxk7WpqrTo=,iv:QXJTNAlozKriJkX0KQvaeX6UCuzzADSctboIPBz+yLY=,tag:4hq9XkEgJE0jgSQGjkLf4g==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTXFKaHJzdDlUZlRTTkhZ
            VmtLQldrZVN1Y1NMcjVIbXpLb2owbTlPTVc0CkxPOHl2M2dEaFRmZExnMXUwMk44
            cmV4QVhrSHRsbzRVQVV5bHFtSmEySTAKLS0tIDdIV0x4VTlscFc5LzNQcy9Fa0Fx
            WWdGejJBK1cxM2Z0ZmhDK3NmSmFPQU0KBON7hfKfDEUEOFQ/aTmPqEQper4LJRl7
            e+su1D5bTAazNmhJ6M+9NjzZ5HGnmZ8KNY0pOacvkHhzSfCN7nSBeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T02:53:03Z"
    mac: ENC[AES256_GCM,data:cZ3hblWrf3QjN9qMqx9vfJjwiWapk2RSHYvUuKObk7Ca2nHmcQy9Ghxx0Ln9XvwWOjHz3pzQMrmEIxtP0pL9BAvlN4JLMWJdtIcfjR63NgH/UEoxEagDtALGoH3XA4gPkYiQkRfpRR5ZLblSbsLPGBtE4HgRxx0bL57opHQgfww=,iv:eBo5ha+LDDmwRDmGuWsGpKs/cSh6qRooiBx/f5dFHLI=,tag:GV2GCdMODux6C+UdwB4yuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
