apiVersion: v1
kind: Secret
metadata:
    name: lazywarden-secret-env
    namespace: vaultwarden
stringData:
    #ENC[AES256_GCM,data:ESmqWXw2SlP+30znYZ8prNLsKmTCS5U+8pU5hH5NEOrHrQJS5zybFRO8jd/mtw==,iv:kQG2Ud+vQ+k1O7pF0dI5iXpYVIZIrtYw3L7EShx7JKY=,tag:irW8vFRcsl4TgVbkiaL9ug==,type:comment]
    BW_URL: ENC[AES256_GCM,data:LFEYT05/TRP8CGe/DYJpiz8QZsGJPJB9F5AxOm/QqcEq3Nzk,iv:PvFriRF3ZyoSu5hT8Bsf6C+oKUEMJssYap2prbGhlkY=,tag:pXm72vYRWJR7wLfVTLzQig==,type:str]
    BW_USERNAME: ENC[AES256_GCM,data:Q6WEndnzNAI/ZGsL+OwDocM7G6O7rVV1RE/IuHa3yriuZRPe,iv:38b/5kcpwPXak4GRDpLwJLb6KPYYJKw4logB6t4w7/0=,tag:KB1H4vFYaCVub6qnyimKng==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:Gqaz2rH71yeCNNOsEkYXwFrIn4uUGovn9VAXM8IJ1e4/Umpq,iv:G39Qvvg94LbO2UNaLKCMRKoATLS3ZC0BNPPZHXvOe64=,tag:h0l4yBFnkIf54SG1yp0g5w==,type:str]
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:l7SSM2oZ9iup6pRKfADuLOSSOC4ToP1xZpRSxWc/jsxAbUA7,iv:lmCeFKi3InC+4vUjBFTiC/D/6Qbcv2xSNNSZMz7Ja1g=,tag:eS0vxUZ3PoPni6Ld8dYfhw==,type:str]
    ZIP_PASSWORD: ENC[AES256_GCM,data:CQWos4auYkti9ntWq9lHdXcSB5t9NrGv3MSyV9iK9nk1GfJs,iv:Vg5Y8vgttl8XVGfxdZNxDCrfLZX6SxUdAp1ldY+htms=,tag:D57BOHYgafSIXcEjvLBqjw==,type:str]
    ZIP_ATTACHMENT_PASSWORD: ENC[AES256_GCM,data:DU+u9+BQuI+jwQtbrRrEyHMxZmHML47ymD//oTSU9FMkFwPS,iv:uz7rvzELsV63JdYxJrCHFgPZXSvEpneQNYSr2K0ZftI=,tag:rNjLAhsGeV0aViHV+KuX3Q==,type:str]
    #ENC[AES256_GCM,data:JEd2Ktk+7fSaUhClQvqmS/CN6eJKQ6PQ,iv:+fgq1RFBSptej+VQXHteUlWOaHz60LrcHhLta3uC/rE=,tag:65pylThCG1u6fMtXnTwlLQ==,type:comment]
    BACKUP_DIR: ENC[AES256_GCM,data:F7YNo1SgaBsepVuMpMGC/SKLFa5y+rw/NVKOFw4v,iv:uTRiMaVZ9j12WkZ+i+y+uUwCyxZKVJKs1vzDdvbEoLU=,tag:rTj+NnWnbqieuhJZhjT6Tw==,type:str]
    CRON_SCHEDULE: ENC[AES256_GCM,data:1mpMBjb/+omowQ==,iv:NuUY/6VqbQSIv4LHANWQgOs7tCOLPoU/OAWRGgnzf18=,tag:v8BBZ7jMDJM6hZ+TiXNZdA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:7KY+o6GFi2XQ7qmHuTpw7w==,iv:AcnBUZ+b0TPBLd4BckG9HZVsZbnUHKTUCYk+JicMXrg=,tag:iuF5jWTLUwlizohlVna2TQ==,type:str]
    TIMESTAMP: ENC[AES256_GCM,data:e7nepOJ5n6l/uTQeph6ApAsVmQ==,iv:SN7XorjLOOjP70kOCb7Ui0E6Dl+aaP9+nnGbmC5MZio=,tag:23K/UpaaXsTqnQfAzxq7fA==,type:str]
    #ENC[AES256_GCM,data:3KCUklnXT85/C4zblhBfbiHc4w4tag==,iv:XfHtsnka63A6HxGD1+7LUbQUYv1wRkwJ/GOU1FTZXSs=,tag:QeGq8gEJeCJSoDAtshB1zQ==,type:comment]
    API_URL: ENC[AES256_GCM,data:53MRoqwQMNd0sULea0Rww8baUUY91gSbkJrgZqwlHA==,iv:FPPT2Lm7YTyqoP/9CUgmRQ66oOXbus+Glk6uZd9AE9U=,tag:36kWKwB9FQlNponGAFSz1w==,type:str]
    IDENTITY_URL: ENC[AES256_GCM,data:QudJTZjeWOJpH3UUwo42za5/dEKMBlvVG2WC8FWQiqiXIXF5,iv:u/uHXHDGjfABIRfR7mhGLoUrGCJcm5D20fE582bSyGo=,tag:hZKMeZ86Y6SdUJUvW4dafA==,type:str]
    ORGANIZATION_ID: ""
    ACCESS_TOKEN: ""
    #ENC[AES256_GCM,data:udbUzYmC+yJifos6KtWrQs9/zs9+KWfWPzdq1t/rYgc=,iv:l/B+kooFCwZW3+6IhxjXGusaAo/DClZuCy4Y11RcPYU=,tag:c4YtHOGcEbjxC7Ds1Rvmgw==,type:comment]
    GOOGLE_SERVICE_ACCOUNT_FILE: ""
    GOOGLE_FOLDER_ID: ""
    #ENC[AES256_GCM,data:oe5wig6xbcS9/PvbMg==,iv:zLOocnRfoWgCgTQUvXa3aicQ9zb/HoIGMziRbO75UDU=,tag:Yrj05wJCsQ0kEu/TnEsLFA==,type:comment]
    SMTP_SERVER: ENC[AES256_GCM,data:9BCe/RjeBsRDxc2KjCtlBA==,iv:iodOny6N64uxQyhxj+9By4dAJVPg56hg/lMkoUo7Mx4=,tag:O76JJhfd59kp+u20izIMWQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:h7++6g==,iv:b5vpckzrQ1RAomj4qJcXUrF8X9OudSGzyMmteFUwDXs=,tag:qZnIT/xZ/20tMKtwINbfqA==,type:str]
    SMTP_USERNAME: ""
    SMTP_PASSWORD: ""
    EMAIL_RECIPIENT: ""
    SENDER_EMAIL: ""
    #ENC[AES256_GCM,data:TJxX1M0vS0asnm0S86+omtTBQbHEcxSEKI5gU06iaL8GN65FaATg2rfR4jC0lqx6B/xaA6+JXjm6hA==,iv:zbu3sqCF0lYk7+BiwRMCz+xx3fTUU8nbarE+Qut6l3I=,tag:z2MHKXM+WGmJozlqOPjQpw==,type:comment]
    BW_TOTP_SECRET: ""
    PCLOUD_USERNAME: ""
    PCLOUD_PASSWORD: ""
    MEGA_EMAIL: ""
    MEGA_PASSWORD: ""
    DROPBOX_ACCESS_TOKEN: ""
    DROPBOX_REFRESH_TOKEN: ""
    DROPBOX_APP_KEY: ""
    DROPBOX_APP_SECRET: ""
    TODOIST_TOKEN: ""
    CALDAV_URL: ""
    CALDAV_USERNAME: ""
    CALDAV_PASSWORD: ""
    NEXTCLOUD_URL: ""
    NEXTCLOUD_USERNAME: ""
    NEXTCLOUD_PASSWORD: ""
    SEAFILE_SERVER_URL: ""
    SEAFILE_USERNAME: ""
    SEAFILE_PASSWORD: ""
    FILEBASE_ACCESS_KEY: ""
    FILEBASE_SECRET_KEY: ""
    KEEPASS_PASSWORD: ""
    STORJ_ACCESS_KEY: ""
    STORJ_SECRET_KEY: ""
    STORJ_ENDPOINT: ""
    R2_ACCESS_KEY_ID: ""
    R2_SECRET_ACCESS_KEY: ""
    R2_ENDPOINT_URL: ""
    VIKUNJA_API_TOKEN: ""
    VIKUNJA_URL: ""
    B2_APP_KEY_ID: ""
    B2_APP_KEY: ""
    #ENC[AES256_GCM,data:6iCMeIQq8asQNdwxb3T04HRXALLNQw==,iv:WrB09fMhIXfwaK3oHnGmjtfT5eO35o91a/sYbHuzOJs=,tag:iWJ4hW0EuxWACeAb6Jp49Q==,type:comment]
    TELEGRAM_TOKEN: ""
    TELEGRAM_CHAT_ID: ""
    DISCORD_WEBHOOK_URL: ""
    SLACK_WEBHOOK_URL: ""
    NTFY_URL: ""
    #ENC[AES256_GCM,data:zqJD06M6Zje5yGxaTSm7RgFqpnZSEBgU0zqryOcMAO7l3t2Esl631I1egPGKKnKAjOoGL2o=,iv:tr6OUyhnQJgsfacgn8atiEInu5RkWcTHBbG7oBHM8tA=,tag:5b9ctskSGFO0xGFIH6N2bg==,type:comment]
    dotenv: ENC[AES256_GCM,data:ZcOI8oPEaCpEK0Wijc5izBKEIkNqbBxSjfN3KvElsr1QDn2gT7589DhLrErWN+x4y4ylHie+ww8P7x9YAwK7WaGvD6gaJLpmJye8r6VyNl0fWVYZzAsGkcrmnslwYwo5hVE5VjEQ1ByLhaGPf4+QHT6q35VqVqIylk/tFAPBaiT+fJqPaSiiLSQtsxA7iTvouu7U0NQFoCxxdiV+PFjHp+LS6WQci6V61XJTENUy8obUXB+DxGcv+7cWa8DfFoN5bqq8wted7wGSuZ1Xg9iTnYb4oQsEoNSwG+qZwdXFr+ki7WFYhqeC/GXNilk+THIxd4B00p7mQDgHJPtpvLNQ3kouCYt5eJAN+WeMKvl9QOfZFPUoPYBJxldY2rNDn8FFFlxwOwDZL5OCXBjOeDw/UNzPLV+3FY8Hwf0+ucbs4lkNRBHtxMZXGZMMZaRvfTZyTXiB9GBnk+yhWGp8ruEwTX+r6y5TN0UYh5l2SlT1lbnBMgVr+mba83B/LVOytzCzgXMrqDjsd2mvSBV4MM66oZRg+JI4tDwWVpaqMPqo34m7p/PE3KCZNeZStiJLxIgc9FdICf9vmETC8tjubjb5YRLJ+TuwGPrDWoUVqHJPPmcW1QLz99jDLRLQZzctW4oJbizHmNvnyYiKXKWDrq4YHF7y1UNxfTFnpM3izZNRT+yc6jyyNxIL+JlvSlhZEXCXr5ZxPY2JgzkD9xaPQdvFIS7f+lCbXB1JYRYikhLxoJ1A3WGJsgXoEtZ4I/CiTGDYbTLp11FFHF1hEgBYdMKD2jWjtpOrQnxkrFpEvgfHKa6zb+Oc3eCwxhZkV99Emd9XuIxWjEVh2Pn0xAZ2TKeOLSjd5MV9g8fmMY9zfK8ssy5gdDda1TETxB84dZeVlSQ5H3AHVkmRVC0RPUOTEYVIEDiYkkT+nbPtIMM/xQBrOjXDBqmY6V7OZyJs9hcY8H5iOi3qeOReMDDp4VN+ZSfRF2GzhhUypje76E4fuP3zlupQCJhRu8RNka7m3gYxQKeeSDv0RmRa74Yrl9W1dho/oXGA461AADPwdyVnd3jAKtEk8vSpB9y6+iV7nCsUkC2DPZbdJL/Q041h4h7S/6RStqlt96+UZGVZWFIxpbJvi0riLEQNhOkIwmikQ44SEnkSt0mmXceXqSAfK6ZqfQKYArhxWmSqEkTDxnxbeqWNjQLruSumNgHp8ZdQkIueLkS/UBduoclzrrGR7mykOX+smQ27q4k+FEUgMQ1BxoZ0Z/iUJbfZi3UmffvmiAos4srhpF2l35FJtvfNHCGUba4dBfozc257vFB+yfVFZSFIiFGZ/OgMQX1lrUqXLn167NcbTbK/+y+EboeyfGnqIpZ9luGgvSknrAaqgh/HIfpi2vLBh9gf0fIFVnt59skgAhf6JjpfxQ+Ay2HySXUYds9uhVmH+uyEmOw7EwUoNmORcEQTR0Ce2GiXLBNqFNG0kfgA10c5QvpXRiMGUfG/VQxya5lziJ+MgPN7Uq7iNiUG+epAYBBWi252xaaEab1RDeylEckH8Uksz4fzd9risya6/ftyOGFhpernnfH2OMaMTSdc/jk+8ZRlFGZovUMPgFk8HtJ/0s8QOP//XF6kt7BqOYpRYUE1ggRyjP/jaTh9d7E7MlmuSAO7x26lE09La4YAkwba0mrxahzcomoli9fga/C2f18YheHRIwysrQumZg4HbQVTOo99INmnsK66w58B3fVlbNrdkraACsm9Ys+ZNsPrRdSCa6cmf2KmKDwQhESsSFim35VysCyoiWidrdhI4nPahn0=,iv:leJlk+k1YmCF2x+K6PlfpZqI1AiKPek+NLajNTv1av8=,tag:FKXDmS3qTtPR/VtPGLHiCQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWlkvdmJtSE5uZy9EVmxm
            YWJDYko1YVJvdmR6cEVEOVp4SkFQMEdYZzJvCnhHL2VRM05KbHJESktJNCtYWG1N
            OCtTR3dkcVlkamhGN0JBL0hyeEE2VTgKLS0tIEFCNGd3enlXRGlKVHdDdEJMR25D
            dE5KYWFQdkcxSXgyc2c4R2N5ejZlZ28KRht/t2T7AtkONDYkl1/JHPmKGlD5QMLl
            F3lx9ccuors8RdMLiBNyt6r71Izi5IuZf9+DMhO8hbI5gcVz2wotWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T02:32:09Z"
    mac: ENC[AES256_GCM,data:nHL4eEer/PxyEHfaapUHEzVL5lKoh0TeJctavwFmCLFjfSyg87PTE5WN7MsWa7bBMc/0f9u70CNJLQskkshnBgVP7smqxVt8yHR3CI2/Np9w0Y7iNOseTy0eepl9OjpvUJmXbTkUB+Wb9SYPg1qQ8o38o5BbZyTGI1SK+0wvhhU=,iv:3JDIykFbA5I0NFmISIRd+jpT0QM3TEpPo2VWv3XmDtI=,tag:HUato2/xOyLOt4ka6gbnmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
