apiVersion: v1
kind: Secret
metadata:
    name: bw-portal-secret
    namespace: vaultwarden
stringData:
    CRON_SCHEDULE: ENC[AES256_GCM,data:UiCYRH8eFDGPWg==,iv:fJe3IJiSZ7NhYQ9TTOMsixIZvgoz2ULee2SfHS+F2jw=,tag:5umG76GCiYAktsJyxQe6pA==,type:str]
    TZ: ENC[AES256_GCM,data:FNUIzmvClsyzxLhtZx/hfg==,iv:rRwbj2DBo3c4IYSOcgdqq7ZYHAZWePEHH9J9cTFEgas=,tag:x6OQoxMBH46KiMBxQ5gO4w==,type:str]
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:AMG0BAYa12eoBytEUQ==,iv:fIX6Ao0fLi4jnLrgelFQuSSIsZqfJ3PgY5LEOS/HsDU=,tag:KgtHu9Yp69DWoudHFSeujw==,type:str]
    SOURCE_ACCOUNT: ENC[AES256_GCM,data:nPExHQljafrjsg1g2Y+dOhKkMw0j,iv:BkoJQmdN/+J1l4ebT1QWb0yBBaKHu9buBFl/yPI7H3o=,tag:IOlcwVpkbKqT7brcWx7aqw==,type:str]
    SOURCE_PASSWORD: ENC[AES256_GCM,data:sm9H8f5X3W50Ip5A1w==,iv:dAJtG5vG91YYHTEvFq5GubrhWprRxXPPWl+fG5lZEKo=,tag:DlXAyOis0RBBcbFo4po4nw==,type:str]
    SOURCE_CLIENT_ID: ENC[AES256_GCM,data:BvqO0K07AUSuOFBLIe+a30Zp7xuv9SPYkHddaAaTDBX87pwOcXuKY/s=,iv:lAxJQ7FO9XxU2nwdWMudddjet2graWwDBwf1SBMy4MY=,tag:BsBG43KjiufSJibYj753jg==,type:str]
    SOURCE_CLIENT_SECRET: ENC[AES256_GCM,data:3lZvhGyG4y9c8P4/5PLr/Ne3qgshkAvi0hzT2uiM,iv:bTHRytbnsr9zHHu7EiWpuD5zc/qPOQvUP2zDg8gZXvk=,tag:l2Lu/TB6lknt+oik6dgm9g==,type:str]
    SOURCE_SERVER: ENC[AES256_GCM,data:p6zdvY9L+H5YB8U9Gu81dtegJdiNwb6hVjdezIo=,iv:dBKLA9V3/wAdsQGxhbB02652R7RZQc4FwZKT8p0gfxE=,tag:PVPOPSIxbMikbV4eFbXzww==,type:str]
    PUID: ENC[AES256_GCM,data:Ig==,iv:URTtX2GhGXnR8oXtdfog451u1a5vP1IldjpR3hSFB+Q=,tag:CKEHL2tWissEfwInpXTU9A==,type:str]
    PGID: ENC[AES256_GCM,data:NQ==,iv:C0LVTRup35/o26YDl3AMxJHDEGI6J/k1J+Vso3jmBbc=,tag:IHBcyk7/UhqfeLsOP5PtIA==,type:str]
    ENABLE_PRUNING: ENC[AES256_GCM,data:B3W+6Q==,iv:/f8hy4LtyQam/XVYQ2M8XVyBCtCkimGMPDKcjwqpGOM=,tag:+M6+63uvH5oXh+3tyiktZg==,type:str]
    RETENTION_DAYS: ENC[AES256_GCM,data:tVc=,iv:KxAuTmskFUMDNGK5ioXb9OeI5Q9ItnQxJs7w3oQe7q4=,tag:ohdXo7tzswoBhav96UR3SQ==,type:str]
    MIN_FILES: ENC[AES256_GCM,data:eNo=,iv:4qgsJPIEaP9dkBk2my8FRdIy203YX4Ftlju00i6UYMs=,tag:eAdR+sBFQU0CzWYRPl9Lhw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eHVWTk1tdnRlRVFWZ3BL
            QXJXTzRyS3lremxnUmNIT2pET3BncXRtUUZrCm1yVGtNUkF2cHp1QzhRcytNYktP
            V3p4cE1PaXFGbHRKcmFXSCtURC9wYWMKLS0tIDhuVDN1MUphVGUreGhRS1lTNE5m
            Nk9aNlhXZXJxRUhkUW5hamRaVHpWbTQKm/N+ZgfmrbYWTT0boQBZH6ZmOgmSBzUv
            +51C6BjuRO7SpxXk7lq8OV/Ajg+qq6nPQj36+vI/p7C2n7ZNcQBaFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T03:08:32Z"
    mac: ENC[AES256_GCM,data:GzDrhJ2yIWY7h1hEszoCUxVerQS2S5pQMSx3APH+0jZAKvw5NdEtnFuotTf/ggrNhEKkcVC8nDIcWle08Ct/pJXnXVsXH6F4747bHcPQUMPp+4iYFMbLzzzl5+z/bi8q+DYhRjHsExNBbVqoI8i1Z7F2N9rXbnQ2gh+GopIMk4s=,iv:wEDufJjJhb1vIXzd9zudavoXkB+m66nKgr5LlP8XTyc=,tag:ux1oUKnfzsCygb3Gb5slwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
