apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret-values
    namespace: vaultwarden
stringData:
    values.yaml: ENC[AES256_GCM,data:0Qn79QrlhFFCCZLYTtymYBABLvsWWbIpQ6GbWSfxzuWOkgry/rvsLtlblG0VOsoLPXbTBiCrq/dLHUVYEkDqhAibOKuRe9S6ZNnB3Bf0KNfDq8oYXflX4A==,iv:Pmj7lsmTc9yygEUXVOxKCMHVMvnhxC7l9h5F1iwf5CY=,tag:CcbtuTkGsxDQBkDN4BpaMQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z0h5aEQ2K3VxbGo4YmMz
            dFVwZHlEN0JoSkZnQkVHU1dWZFdWckVxYnhjCkhMVWZaVnp1VUdYYW1VSmU3Z1p6
            VVZLVWJSSTVoc29iZWl1NHRVWVFsbjgKLS0tIGZ5L0pJYUNIMFpTV1RZQXdoTGFJ
            c1FkRFZTZzZocVpGU2M0RDd5Ulh0YVkKX+koZ/uWqz3BiYHGRASxLXdxf373LelI
            DnfdfIXe8PVlOFGAORcvC8O3+b0mhZXa73xTw6bJt69SUuCfRvwgAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T19:55:14Z"
    mac: ENC[AES256_GCM,data:QCN/BzyFwXZmLwuSumTVApB58i1D2AdLSUamNIJ+qbL5sso89QfJhisU4ciIDLttKyTwo/9d5YhMCS44FaxP6mZ/4y1qxEPkOXGuIxlo9e9GH3/JxJbkjZFYoTcyOrxRf1gggVwWrXGWVC5ywpM5fm86NzJTXrz1w8jTw64j/6g=,iv:G70/RLGOv38P9VX6LoxUE0FIwiA6QBq5DIMXIL+mkUg=,tag:Yti/b/+l9OIuctJknPIEHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
