apiVersion: v1
kind: Secret
metadata:
    name: airvpn-secret
    namespace: torrent
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:7qpV,iv:ZA338laXbJ6xHsLZTWeNKcPAO1YruoScpB9hGq7jPWo=,tag:hDRgudw8cSWvDgG9Y5aN3Q==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:OYuYBiGW,iv:egD33dJP4DnjX2wUaR0zhQU8OMaoLBVBNQoDhf1wnQU=,tag:61dYMOHUhtgv4QI2n+dRkA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:mUWmnlKjaiTx,iv:iNN+0E/4kRXGNxXx0h9LHNVJSoNk9RB0S9CXq3D2Q7c=,tag:+CpASrBWwfMlqdiz02j/Zw==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:2ztyYekJayuoA0Q=,iv:lSvapHqwIfhQ8nK1IVvLwhrfePc9OzwBzymXRO8/U9k=,tag:BKXGe4OYfpuUf6HPUMZDhQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Gkl+x90nYD+J67F37bsDlGkPAem7PfueeC2s16Yc4ZvaypaQHaxYj30rdNg=,iv:Kd+DPPqFUGBZUt0JA4qdEkbXgH4ktgoxV3arz9y79+E=,tag:KoqNpXttnYood9Eoqfz22Q==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:uwH+aj5yvXNsHPwIn8PysQ0KcoM/vKC0pjGrm5qiHo2XEelrPPnV81s8/+s=,iv:OfmkomiQ++heW8yyLG3d+Q1c95fpoOI4DWFZU1TZtxE=,tag:aWyaOhnwdNHI2hqtYPAKkQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:SCZSRxdDFn+tGCxAvBCqbW+cAzvC4Qf7BYfZJwCqHdcCp4fH1pmoVgBaS+QQZmV8qtUUcbkkR6XeH2pJ,iv:ZxkCt1H8PXB+U9kvT76uTtSkrehPdk5Anq+UR6/1MM4=,tag:R+ApM56r0U4AC1nBJGAmqw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaFdxcWVUMm5OT2ZWcWdH
            dXJjZWdOOU0yY1NEQ3I4OHZzMlZmQ1lVRUNBCnowRGNiUm5HWUk1NlQ5THJEaTBo
            S3hYOSs1NWdiV1JpUEVUcnBOVE9GQ3cKLS0tIGRjSjJBenErV3hiOXlKbHQ4bk05
            VjdIVXZJN013YXFHQ3VYM080MnZISncKvhawHAUU3qHWHYP9+R8VWptkGSXUebne
            VJOgvOUxd1TsVBD86YPslB9gVYr3XoOg+9sztsmy3jhcaPdxbNznEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T20:17:02Z"
    mac: ENC[AES256_GCM,data:EHjZfbZti1oBIqWlt2iFXuO4fJ6R99Ney2OrigDeL2JOZeIML+x9IqHnTW56gykuQT5d8/XBiVg7jBpkVwCJJIEkjXZpdoBaih1Wgfs6jJqB2GpQgzeNoIIoxlchdHG06WsEKKXKsMuGlQWRAKJNmGukNsUg7I9gVPVx5r33GuI=,iv:ttFR+bMPTohRt6Ih4ve/hnO/gT9dWq2twB64XCpFs60=,tag:wiyfxhH5NfzxVAZlpUQq6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
