apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-admin-password
    namespace: rook-ceph
type: Opaque
stringData: ENC[AES256_GCM,data:xxeP1uyw0wsL8A==,iv:bwIZyp3J2UpiDb2WxPN1tBU/IIlcyW3pq+cfy0jNFOc=,tag:Tcmb683Rb7DTmmGrcub7hg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVXdaczNBUkx1SWg3WDJT
            enF1RVhDbW5BUjlTTVZKb1JMOFl6YVdobG00CjZIMHRyUzJwdlliVDZuSWhQckt5
            RU5PVzVxZFBKM1ZFQmtGKzFueklLcnMKLS0tIDJ5U3B2ajczVUVQblZUOXNLcTMv
            M2VBNklOMkFYc2lLRktkNFN0eDdiMUkKM2bq1lG+t/vrAqykXNpxY4ihtY5AYQJs
            MZioOhVGztqcgKtwyKjH/j/hxVuzbsKGMcbrUQeirZa0VG/l3+PoUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T01:13:50Z"
    mac: ENC[AES256_GCM,data:XpDeEbsyXXglQa1b/NOCDW/PnJHLPrfs8yhfWtfkz28/hgk8V9zd4dAJew5RxRJ5wHGZx9eqfi/9KFG0O4ixf/unqbhgsqhKOLIts+b0zo9zCV7OyrOn8CziDBWbOGsuimftfe4XkE6ojP0HKhWX9k1J0f9q+OeUFMngsW5tL3k=,iv:MXO5IMFOSlgsEfzJA3KASAckbjmoQYT/szUzXCK0/EU=,tag:15sC/Hj4AUyVzgot28O2UQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
