apiVersion: v1
stringData:
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_PASSWORD: axGzRERYlVu7XLqO53a6clBAD6YqBvb9j5ww6AGdynk=
  username: immich
  password: axGzRERYlVu7XLqO53a6clBAD6YqBvb9j5ww6AGdynk=
kind: Secret
metadata:
  name: immich-postgres-user
  namespace: immich
type: kubernetes.io/basic-auth
