apiVersion: ENC[AES256_GCM,data:YaI=,iv:wePH878VLoaUbDwGyyt+4FWUMQA6D0UqxA9q65M8/VA=,tag:c068q/VWlSvxvWfWSdlQeg==,type:str]
kind: ENC[AES256_GCM,data:gTWFxP0i,iv:biGrRUJMDImUiTjzJpNeI+qQ1EQWgFeyibs/EeAUBdM=,tag:UMWfDrzxFDnySvOu8cjEow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Owvr/oosLjJvqbLwPY047iv+BgI=,iv:CmUgDBWhrt1NJtPqLiHDzeHOwaLtib04ne2fShfrt74=,tag:CatJyctqKZSxtCt34EUZjg==,type:str]
    namespace: ENC[AES256_GCM,data:pLcmhkcsmTo=,iv:7T0/MYYIIdavmYXCvOBfpdF9wbBk9QoszxAPusI9QJc=,tag:85XzRYznSqAKBunlo8NNTw==,type:str]
type: ENC[AES256_GCM,data:d+Yed1xA,iv:KYDF6I8uIBkxAsIglgeAUgBMfkdTQd0LH5go1SVBDbk=,tag:ojWOnwXP7zwx2cSGvE6BsA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:m37itScFfLqmBncNU5EIlEC9t8gLzn3ouzy1fsls1kp2iooWfXG2VA==,iv:/rU7ZZ4W3wT//bD7puObtwMMKhX20ZwIkBteyTGdJ/E=,tag:B46o6SQJYckonoAmyumk6g==,type:str]
    clientSecret: ENC[AES256_GCM,data:8LW98sx3/oq/z/3vrnt0nsM9yGXqmBXq3CCeMy1xUb7NloyE3fNVxjA5nS8Kp839C3AhekRs1r+MLu2sgostOFW57ySnaCrI1NAp51jhKwOUzXeasHrIxHCZzY+YOeEClWSvWzw+dUhhsBmFlXUHeLeD5KNN0by1fZPgrqFa0DI=,iv:NF9BBcU5RKXgCFKweNdtzt1KhO/qHYAEhuwCwnYzVQg=,tag:0XzWymsowEVFxNsD8yRRBw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTNLYW1OREd2OGljTFZp
            enB0bzFjMkRMZExWOThDVWZmYzdmcjdTVkdJCm9RU210WWdZaWR2bU42d3ZMMDRT
            OUhGM0hQeTYrK05sVjhyZjF5bnBKY3cKLS0tIEsxekIrZXZYR25LUHBkSTJ6anM2
            b0VOUjNrNDlDaEpYeGtLZG4vREsyYkEKmuWAgv3qZ/Yv99I2c2gYSpiNbgrEFnC/
            dkhfPaqU8ssBw9x1r6+1NkFTsG91MXnisiaP08bPMSfmtHtDap1oGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T07:22:58Z"
    mac: ENC[AES256_GCM,data:/wnBRivlVhW5i3OG3az4TRMeZVkIcwFYTPjhrtNyMltti+8fNOXWM7oAlqvCSa1Rs1RFM+NrT/mjn7+LyKeU90XcF15+ijE6qIinqt6s8vtlki8j21LqL4URwMB3il7yh9+wt4QvHN9y0Kz88vJ9LQKhh9RlRufVNnZ1i3gtX9s=,iv:K/jZ50G0SBe6lEJjBJDU85DkfQzUZnLP6HNzr1WsnEg=,tag:Q01TIZy1sZ89LT95bBie8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
