apiVersion: v1
kind: Secret
metadata:
    name: pappwiki-oidc-secret
    namespace: pappwiki
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:l+zX3QAs9AtFdDM7Nn1p5piBpEctYOCyNmRqoCwoL5P/rytNQZra6w==,iv:106juQyQNtgAq2QZKHkrzjjvBb314yPCdVuPQKm3iNY=,tag:wihSj9yzlPh0OIlfN+NX1A==,type:str]
    clientSecret: ENC[AES256_GCM,data:cXtHn0CeqpcBGmReXAoK/bQSDUt6bAT1ZL0Hcyt4yjdSRQ0xNu87CQfB3O8Acy2iKG74EQ6IMipBkCC8MMUIXoid4o1LL2GKVK0c7tnRsjkKnDWNGL2uybldYuFqf4t4eGwqGWtInp+9cUE62B488a+y4XBNWSuSx4bM6FkuyP0=,iv:bJ/criZXyUAOjCRGVcm+U7GuFfVYcjFqFq8XhN0u0+Q=,tag:Uazq810RK3gii2xj3/zkPQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSDd1SkpKZ1BvKzV5Ui9X
            eEdZOVRET1JBaXc5TkZtc1N2NDE1K1NNOFRZCmNwd3ZPYm1YR3A3OFZJVGhlZ0Rq
            bWdCYjh1S0JqMVhtWUtJMlJHQkFlTTAKLS0tIGU5ai9icEpTd3kvclAvZjEzWXpQ
            Zm9xK3ZUU0tpOTlaQlBzZ2w4emhTTXcK3xVkDt7KXI6Qao/rdDIUjBH3kblWwHLW
            TbJ7/d1SUMQ+BmGgTmMv7NYd8q+RamBmtj3CsS/H+i24b+ym5nXiNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T04:20:51Z"
    mac: ENC[AES256_GCM,data:Dnz0NBLXCrZbZhEJTWpDD8hieO3k/2z8abZ/ugsOTAel0genmPU0RB1qXY7bbMYai7MIiXqbbKY8uBnKL+sfWvO1PrtDVHD+nU2X3hnM0/SbBW4r+yXB8NFlAKLXz1UR89ubpQ7VkQi9pCtY/uA/HvmM0pash8mggJTxuPNfwQA=,iv:MLfdkNqWjxnIDu6lzjRsUMYowCq1LGJ6Z8bNwKQv0n8=,tag:Pei4ZD/8Kwxi/QgrYNJpQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
