apiVersion: ENC[AES256_GCM,data:T50=,iv:BSslB9RMQ2A3TFWpEoxkZ+7SkOwYB5E/0WhAJSZIRCU=,tag:eDez6ckpwsaYFtrQla1AtA==,type:str]
kind: ENC[AES256_GCM,data:MAQaaxjE,iv:gSFuy3C6rWRSYjG6qNUjaQ9iDxRxLk3x+tt4k2vj8c8=,tag:We1OLnPyYNEq0Cs01G5PoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:51LCPhVvnITwJ03OV/r9zAGJ,iv:MXj/kMM9loXjk+9rxQ+rUYscMjfu2dcb4xE4dlub7RU=,tag:eozIh0mHMbrVxTTA5knBRA==,type:str]
    namespace: ENC[AES256_GCM,data:GBrhjeXFOns=,iv:SGEEb5SVJ2mg9Qn3otxoZuAyJ4ZM3F+h5ZHeW7V4/ow=,tag:bkIjplokbp2bVS/J4U1X/A==,type:str]
type: ENC[AES256_GCM,data:O3lQFU1S,iv:jJgXjuAxFJz9FMqXHUSOKe34D++yZ+gJ0D9BTtGAWkQ=,tag:3bLrLcB5FRtVh8DgbbMWcw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:VtXN+EOjWyo=,iv:X+OcHU5HyV6VjGPnt2j09yd3U66USOSFcuNe8KniuHo=,tag:f2LU0JAmqJPBHcTiWGJEtA==,type:str]
    password: ENC[AES256_GCM,data:GU8W0QG6PPYS6wz9Sn+ayL35EXb9240Gdg81LyiRLDE=,iv:cBib81/tFBUkN+vh8jfXWRsQzQW4vSNHIrQ1HrbEZTg=,tag:cvY4CayRn1VtdMf/DGxthg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGam1MeENoYXVpQTFscjEv
            VkpFL1VEMGtlRUc2ZWtWakI1Wm9lK2NMYnhZClBCMmU1R0tHVEN0ZnphV2J6ai92
            azZKM2YzRVNobEUzdEFYMWdPckNQbVkKLS0tIGExRUQyUm1QdHVJdnB6QlJRWnQ0
            azM5bXhaZXF2MVpRNGw1QkI5ZTdxWWcK+eumvVMcmDj/EiGYEDDQ8bC5LHqPtyul
            JVOaPWwrG6JoaK4AipO2HBnIKHqgWfLebZeRLuHWNiF2jxdfLT0bnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T04:52:20Z"
    mac: ENC[AES256_GCM,data:xZKexFcAlFoZV0AP1VtcCtgqCtr4YpDM7EbrwUCIuT12fsRSTn+3iTTJ572UdwNp35wOFLhAk3eJbxjBphlRA5owXPP/ZNfr3HkIuYj1CUy2UiVzqERVtxckAQJ1v21p4ra91TPXrXTnsBFHMSz5hOW0Te00lvMQdjknjqgRvMM=,iv:jR6dZ5DoBxa4D+RiTCwFTPVKQ/mZZVKnJTINK2ceShk=,tag:CUSsKlAw8plOuLke+YYNyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
