apiVersion: v1
kind: Secret
metadata:
    name: pappwiki-db-secret
    namespace: pappwiki
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pj9Q8sJll9c=,iv:DSfS3u6fw45wB+Bb0tZ9VKnO4QIOXj+Ppi0CU4jvAs8=,tag:MJ3EQExzMpdC6bEqgkuSSw==,type:str]
    password: ENC[AES256_GCM,data:ngB6e4CkwBf7m1anF1MeEssZzoTr0w54xG7NBXlhQG0=,iv:YolR2OjixaicWC//H1B21dXog7NjNvykV0Z7PAslQqg=,tag:aemQ0VZgU+SOCfyWgsHHPw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNVY3YUV3dXN1RGU5YUpB
            dVMvcEJhYjhoL2ZMU0hWTEhzSEZyZHhDcUdrCjQvd3I5Z1hUK3BxMWlSNk5mQW5H
            NmlNVURTZXVpZHZuVktRZE55OFRwOUUKLS0tIDhRblI3aENRVGhJTkhKRllET2dD
            MDN2ZkJ4VzdYc3ZHMEdnWTNkNndETUkKjwHLpRnKq6vs8oociVUtLb4nTbY6Atzu
            P0qk6O4kX7TNu6MC+BFISuKwwifF0dFHBILu9o2JhSasX0pt/Ph9Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T04:20:51Z"
    mac: ENC[AES256_GCM,data:9NLO+1HiBVpK6lZ0ZC/F5fx9GrLFXrBhwyYqc6eOyBpvQH49Ac7Q5V2kr5R/uaKqTpfRuMRvbWBDcEwe5ZZ+UN5V6L+kevOc/HZgAq5cZ+z42x5zJuwbphNJwdVGAjMPP+0F+OHf0MNVPBzigiWsSsZxxMirx973OS2BkCt5M0I=,iv:WKvSi4cen2+GAr+9B7LiMYkuVGDdQGmxlKo6kJedkqI=,tag:jqAzV3/Ce3A+y+exvSukPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
