# Encrypt after editing: sops --encrypt --in-place secret-cloudflare.yaml
# Use the same API token as cert-manager (needs Zone:Read, DNS:Edit permissions)
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:qPBXQUT5rCxNRuKxzgkn2hLMm5HBWR5DP9pPN+IFAo07QKWQ3PKcIXTEgTqkmQP7yZKo/ZU=,iv:vGs0CwpmKHPt0971VhXbGU5RoHVGSPXuAVrFDhwQvd8=,tag:TRTuBiu4Pq/QI0MrdszOrw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU0liUG1KSXB0OXlxdEZh
            VXlMZVoxUWdnWFlkMmhJZERJTnNTWTZTOWlnCmNkTEJsVkJGeFcvRTJiR3paOXZs
            a250RUp0ZUkxRGlXTXI3a0c4Tkl2Sk0KLS0tIGdFcUhhZVVmb1g5WUhhcThpMWNJ
            VDJpVjRmZXJqVXY0Sys4ZkcwMGpyMkUKKKevBEGwecKZjobPFAy22gchNOgbWpdQ
            fYj2ugTOlzV20rvJvifrkisaObaa04fB2GjGLb1ISU3K0zsGMelqaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T21:24:53Z"
    mac: ENC[AES256_GCM,data:wDxaOZr1QY0FhIlwjeTVjCs/3ZYsmbz/iZJo4aq2M/TsxgPXEsQnDkI2QQh1Nxui6V2XKYak3zbDC8WN4aDyPVipHfJy8ZCw8A0ea3DACTm0UH3WIgi0RSM17biJVd5kyTiX0sbF4Io4dLFcJGxbt2lfTDKQ25Nc7GnmsOEud9w=,iv:iGRkp5AfOnFiv6XFrRGingxl1Tf/Z8PxziNFOdwFo64=,tag:4Dclo88u3T1GQ6TVY/C0WQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
