---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: payment-processor
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/grendel71/payment-processor.git
  ref:
    branch: main
