---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-vm-rootdisk
  namespace: kubevirt
spec:
  source:
    registry:
      url: docker://quay.io/containerdisks/ubuntu:24.04
  storage:
    storageClassName: replicated-x3-block-store
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
  namespace: kubevirt
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-vm
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
            cpu: "2"
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-vm-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: blau
                  groups: sudo
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFnx/ZGyG6ED/Pe1SUWEDeGhuAl5PV6thdet6Pu9p55z blau@blau-pc
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-vm-ssh
  namespace: kubevirt
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: ubuntu-vm
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
