apiVersion: v1
kind: Secret
metadata:
    name: mautrix-instagram-bridge-secret
    namespace: apps
type: Opaque
stringData:
    BRIDGE_APPSERVICE__AS_TOKEN: ENC[AES256_GCM,data:8UBzGTNMbtrfPCoin7hxNui38hALNwoUvSy0iMv1dchSBb01ZJmpsIMUsEQgIOLIDlKoedGMrLHj0bB4,iv:LSyJ497VNT/CRfpgP7uu8M7XYL/k62Ov3KOkSYnxnQ8=,tag:hkZMQMPgjIpusScVvpnqKQ==,type:str]
    BRIDGE_APPSERVICE__HS_TOKEN: ENC[AES256_GCM,data:A5tK52UBg62l6y5iB4WOvl4TW5S4iZjfX07SWceb9ehMNZw8xCBPtR5+TVwOtweaswMFeR2PDgXMzuuw,iv:1n3vfJtX/X48n0d9Pek9YGpmrreMzniR2XX7NZhGq7A=,tag:tCONloRkLKJVMXK61dQLDQ==,type:str]
    BRIDGE_PROVISIONING__SHARED_SECRET: ENC[AES256_GCM,data:EFMJeBeUIZJawKHK0VsrbrDq98ca8bIhZB5zEyjhGDJQX4QoBsEbuQ==,iv:NnFF3qf849Y8DhcFkrUEDN1R3TJuUkJv3OerjeEaMAE=,tag:y+Kib6pQlkB4pRAzsabHrg==,type:str]
    BRIDGE_ENCRYPTION__PICKLE_KEY: ENC[AES256_GCM,data:pcziU6ziyLr/tl4/hN8hCMoGE8wc0caGz59h8zQ4iOUb+KGdaKilnw==,iv:bJ0sYl8akCgd3RNyRwV/e6hGanpfmFRxTRAjqh/bEN0=,tag:GiWlWum+U9wCBQ/COnKNHw==,type:str]
    BRIDGE_DATABASE__URI: ENC[AES256_GCM,data:BGs0AVm5lnxUJ159SxyJyMasQPtNx7hLHB0mBbftdRWnrsUsBdSj9LYXYsZKpjYC4+I3ghysuQcN4qGNm4JqyHOkZtdRMeiZCaN6T6IU1z+XneFibvjmW4q3a+VKpnJg6ltn/z4cER7mCwTZgZpt3S4Fok5tJMpj2nx0FNEM2ueqpg==,iv:hwqwSCQCfyloNmNa7+p5IUVMcTWmKWyTvT05EoTNnXA=,tag:qQuA4Uojw0mVv9OZB4mrTw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU25nRG1PY1ppbXk1QnBy
            YlJ0OHlwTUhhMTdtNG8xRkpJd2x1T3JnZ1IwCjBYQnQ0dXFmZ1RDcmd4UEgwajY5
            RW5wVmV5VEVRZHhMdmlYK1RLNXJSNEkKLS0tIGdtcDlBZ2RrSUY3WUM5WnB5TUd0
            QkU5WWV5YXRGM1kyM3JvTkJCTlRjeEUKVzTLKR0LcfyFeBH71QNAvt8qG6EA/xfK
            gHiLEhLNYYvnyQRL6iSFsnChvz8C/7GrhOicNQptGWE773waC9QQ8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T03:27:15Z"
    mac: ENC[AES256_GCM,data:1Ph6FTqDrj7XZq7OBScUPqMemsU9Zo6l5+CGix1jKsEM0kJp8ULe4w4ksdUfI/O5HDVU0HamtUTDyF8o38dXAowRTRL41xHt93dmTu9ljhGmmSwND5iyhPDGm1A6QlLWegmkaZ6XXf0X9M0OKiJitZolGTdM+q71DsLVUlMVTKo=,iv:XEBuiEDMNpy94uarJcXl3rwD6VvDZ+eVSHy3ro/QI2U=,tag:zU4lbRdSm3nx6W31vdjvEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
