apiVersion: v1
kind: Secret
metadata:
    name: mautrix-instagram-db-secret
    namespace: apps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:n+4uwWguLnK7yew7oyT5XQ==,iv:iK1Cw9SOiN+HZPNkno7QQGq2XLnf0Kr/BNnMDiaYoig=,tag:Mj2yfWFdpEFB7X3LQhuZ3A==,type:str]
    password: ENC[AES256_GCM,data:9lrNnVjdZ8lHnmAMgzyNpnxwAXT3RS3oNxphap/AYRDm8G+hR2i28A==,iv:3VatDIDrDiAcniFp0t1JIaK4INc8Z5Gz92hy7hDbNJQ=,tag:ezkYEpXhxaSRE6phzUQZhw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WXMrd3RoRU1WTFpGd3Rh
            bHlPZ1lvWjhpMmVyWnJrOVlmQVZIU1cvSUJrCmN2SlZhSlZvRXNzZWhrWms2ZVU1
            VnkwRGtYdzFyRHFVVW1ueWhWdFc2OTQKLS0tIFpSQVZCY3hNY0RWeUQyZG9rdjNq
            VlRrb2w1T2xzTHU5a2ZRQ09mUkViWmcKRDPDW5Z2aj+DlxifCimoctZN0xAEtYHJ
            yh0d8XmEmGOf5PI3JvrG22bHj+KlfdhGfqtviW/Eq/ChP9QEyhy4og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T03:27:14Z"
    mac: ENC[AES256_GCM,data:jx1kKkFl+K5+HVeYpN2HX1x0n8M2ha+Cl93zTGot8zfe0QS1AynliVoFxUIRB3MRsT24MX1uuyIJiL0U7qCyUJ4xwpTUZzkZsYULAcwL33frGROVBWDf64tg9YGfPvEVOEE6qg7tZmQi091gE7wMzsVfCzWGSp2XHZZRifSd6ww=,iv:DkQL7Wz95m/I2bZ4jZiuwhVevfeGk2pqjP99Ua4wzQU=,tag:6fLCdrGik5+rD26Dpmv6Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
