apiVersion: v1
kind: Secret
metadata:
    name: mautrix-whatsapp-db-secret
    namespace: apps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2FAYWAdENQ0qW79AoF6Z,iv:EJ+VMrDlzTuYxsYH+3Mo1M3v7Au+PIRkzHj3EdaQvMs=,tag:5n8+PHKBRVbGzsAntS30dw==,type:str]
    password: ENC[AES256_GCM,data:rgQ57ZImZiZHgbU1puIAOn3r72HI6ijKNBPBPSLZOJ1rqZzs1+skBA==,iv:GdFGFa/UcMAMOHj+NjcE9v91ze3gon9gpo7v3FEeRVI=,tag:LCdXXb8Se3l6lJXCjDVOew==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcTVSZEh1RXcyOWE0Q0s0
            Q3U4L0tNZVpTcGUrUkJya2ZJT0ozUUQxUENvCkVkNEpQVEpoUDZmTjNxRFh6NWdu
            WkZkVGVyUWYvb01aUnU0VFhYc1FCMncKLS0tIDhQZFFXcEtIeldwN08xaUxROUN6
            MGdxUVBIdnNPdTVCLzljM01uUWpaYjAKoqXQPP5pGcQ8VM4k659Z4hacYeCghtuP
            /tLG+poFQrqalFPD5NhAz1VwXYt0p9+jJt5Kk5u0K1PIWwTOEHNtGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T04:21:22Z"
    mac: ENC[AES256_GCM,data:/EvCIG0NbQM/QR9xYYAr/LaGNAzds6xAWYalO5KKXHEhIIhMqf2aq67WBpESMEgypDgQa/I9tA/h+atOhadcZMu9PbfxOTRnZRA4Cf5NEG31SbAbBa7yjH3X3ihS7o5+BZPUnEIAGwAfcVEbg+5Gws3LZnBizWENKv/MVTjVYGE=,iv:jmmC9uk9AM0sVNFVtI7VN7z0KIRPH/KrFpi/7yc0mF4=,tag:OE6omcjqFOZOtmQBGjolug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
