apiVersion: v1
kind: Secret
metadata:
    name: mautrix-whatsapp-bridge-secret
    namespace: apps
type: Opaque
stringData:
    BRIDGE_APPSERVICE__AS_TOKEN: ENC[AES256_GCM,data:Fd32lD1tVwyTDG8Wfayoy3yOrWbD7jAyhnw15OFJomFjj6z8wdTLEVmBmQHphlQdsg+vcLAxEr5N2C74,iv:2CeC31rZrnh80AlyVvekkf9rae/r1CwbbUTVbHAax9I=,tag:ToeNSiMHLobctY4yAkwTMQ==,type:str]
    BRIDGE_APPSERVICE__HS_TOKEN: ENC[AES256_GCM,data:MitXO/oXvc96DI2dPviKCU4VO9ELLMZACkVonNK3oaxeV9t7bd3FxbFvS8v7YcrQJ2byS3kqTEqHDUG8,iv:BtM+TKFT4KzPBgS9n8CCPvv3j3iBH9h0wxSEFQYfZ4w=,tag:zuzmYHU1mMQHwU3fRSOYnQ==,type:str]
    BRIDGE_PROVISIONING__SHARED_SECRET: ENC[AES256_GCM,data:oTeaXBtY8228Bsg9oQYhE47a8xB+qC2gHRLO85L8GiSBiw7MWzcZhA==,iv:jaTIHgiEx/wQQSFo0e7AYyxoLrw+r8IORCgvjuapJFw=,tag:5VbCUoy/KZPqYU2J++/RqQ==,type:str]
    BRIDGE_ENCRYPTION__PICKLE_KEY: ENC[AES256_GCM,data:L7FXH7uPRC+XdYTRd5PpxV5Wogf1aQS1/iF122r9qc5lRQ0H6JEv5g==,iv:EV9ue6NpEr59owFWEvVW5jLqnSR9FVbaBXZDXYEYhME=,tag:yR4x4pi8U0NS7VmiviAAcw==,type:str]
    BRIDGE_DATABASE__URI: ENC[AES256_GCM,data:enPnHUYM7IJpMSlGkvs156M0tbdjetsxXkMj+eyzLg1XI5/wDosOGLOsUZN+jHSTS6GSsJg/qwIdGn9CYhI/RJi+qMfh7lEI4oE1rpw3JlJPPMyzHv2ic5zuifapbwhcYVxYlB7Ht+8FtH8b6lUqTrWHuHW31xTPRsJLpBnTDA==,iv:I27PksPvu68HakJ2g32PZsyB9UC2rxkXcpapdalISJw=,tag:d8gpKrbU0O6g/kjs3T6J6w==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa2lKWjREKzY1VlI2WFk4
            b0xqWVBmYklIT2dHUG1pbFZRdjlDeWc2UVR3Ck0zTDZZSTRQbno2bXFaUEtSYXRn
            YXdYdFBDODducDEzZmhsaC9TRE1IN3cKLS0tIEtOeDY4SG9OcHAwbzVxMkZ5aDJ2
            SVRpOTFVaEtCdXBxakNiMGxRaXAzQUkK64eIhJxsbQA5kKBuRE7IT3aTy4S/nZPi
            b4C1iS4dkqYwBgZVBgv0t0rQsglaacfBPuyq7g7xYLWm80NNhzrL6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T04:21:22Z"
    mac: ENC[AES256_GCM,data:YjsHFkYalsv5BWOjYuW0fDn3Nl9K1NMLWovgZdi87OvsZUVQeoAedhtOTGzNR2996iFDOOihvRdQrToE+mvTM9uushRk30pt/aZJV3ximeVAbqVR9fa71radQ4bUUBjHhNrqyadNpDSdIfkUI1m613LkgMJjaAa8pQ0LkesdHX4=,iv:cFMrnG2kj12pxxkg75DdB1X3t7x/UiZHfX7T9wX6ZYs=,tag:zYUpKycpPjD85R+9xfvnDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
