---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  targetNamespace: apps
  interval: 30m
  path: ./k8s/apps/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespace
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: jellyfin
      namespace: apps
  timeout: 5m
  wait: false
