apiVersion: ENC[AES256_GCM,data:iwo=,iv:YzXASTqeMZdyY+Nh//LqkU1mEng4GMr9aNMB3qbrrY0=,tag:lo2F2/8JioXg5gLugSYHRg==,type:str]
kind: ENC[AES256_GCM,data:4UAaMb+u,iv:6plbZ23Gmcy6W7GAvGM/ThiZ25oaEfemB0Vbtfkam4E=,tag:uIVPgo3fHU5uL1RqjaY5DQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gG/z6aqXZXKy72YCWfbRNdcf+kRmPnMr31SF,iv:lQ7+Y3CZczUwJuwqv9YxYy1ABeQ/G0hsdngc/d1h4vo=,tag:VBYTBTXCR+gVcUGB8/16ug==,type:str]
    namespace: ENC[AES256_GCM,data:yDijXmdcy1J0gy/D,iv:Cmyakwa+ASDJ0g+LzuUktWr3IjekwqBOmJCf0aKFnlQ=,tag:hpdy53fCrggphVE0uqR5Mw==,type:str]
type: ENC[AES256_GCM,data:MscpFVDZ,iv:pKwkFP9iRFqdykccuMg527+26pXsBpCp471VmCaxS6A=,tag:UoLPpIO8EVtUGhhwaX07WA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:RC06pOTWvACPWuWGfKDd8FAl3zbw45L1U8IlW17is6Kwu+zlTix3ug==,iv:Jw6kuu/+D9ze0ugCpl2Ne+UYuC54F4FIvwo3je1GOXw=,tag:z9OHJ+cyxMvc9b8v5dg2gw==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL3pydUNUdklaT1k3Lzdq
            WjhYaU1mVWFGaVpYdkMvc0tZTlNMRjJUb0dvCkc1QVNmNjFWWnRWOXBwT1Rvb1Za
            NFI4T3QyNXFZQ1EySWh4aGV6ZXA1cEkKLS0tIHJxM1p6dlNteGhjZE5uT0kzM2s5
            ckhudmZkVldpQ1NpazNWang1NTAwL1EKt4tT9vP0DoMLuUlpEvZsDdyP4+ISHawl
            taws9Q0sz6Tr7nERm/X5rpqABSl9uFfCbIUOhOoaUTjB4sZQx5K17Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:44:03Z"
    mac: ENC[AES256_GCM,data:ZEmGYhuEPe+338u0Q1n62BL7hA20RiujD7Poby8jvRo4Y18aKLcLuyzCz+s40PW1vTcmd0aaZh+vL28RFBtlRbWv4s4Xt290IbIASwwlAkQk6Caecqv2/Roaja3iZpSluhsdDd0G/57CbCXOI7oYcOGNW7mGZHmBtkzaW5b8Wd8=,iv:UZWGUJgORxVrov4wQSTlYhIAEL1U4fpJOn4Vx4+//Qc=,tag:5AxbDmXFXbdE8lVNvcpMEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
