apiVersion: v1
kind: Secret
metadata:
    name: tuwunel-registration-secret
    namespace: apps
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:Sqs+JUNczIQ3dwOrRLEDnbhg+2eBL3VahlrQ/MtMVTc=,iv:lGvT1M6Eu/4/qrJXLdmAsoN4TlW+YkReUXdKmN7l6YE=,tag:WL3KdDsvNDgYpojBH7xncA==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOXVGY3QvSFZKUWZYVUhF
            Q0UxdFRySEVYWXh6WWtlQVBncG11a3VrbTJNCnViYW5GRUJjcUJmc2lCV2h6Mm4w
            T3JrYzZmcEhSNnp6NjFmcVpSMU9yR1UKLS0tIDVqRDE2U0t3bGgzU1hJQXNxaU9v
            N0VnNjNXUzBBRVowYTQ5cnpvdUx1V1EKd4lsGDkg/LBUhIHmAGd9T7ET3wmrb0Gt
            2mpNd/hWzBftYd28bzQoYCHJQ5/EmUK6Snx94tMD2t3P8dJ3u5viLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T20:10:37Z"
    mac: ENC[AES256_GCM,data:8ETbLkymb4FRJQ1fpbF2jI5XvAsIVgLAcLBsk7wWwKXo9+MBeN5oDMPPN1e4kyT31VnPRHymjfF9KM6nBP3Z/vYnpJr6VckDkto7g0DVLlU9Qk4k6IPOipSV1Vib3mQfd4X3tPfoyvDOcODV47itrNsxgZU6QEbuE26UKSkXlpM=,iv:I8AO3m5N50DRITlMn61WnoezikwMEK3v2lf+uoggRoc=,tag:Je/lupwavfGNxMmzSp4Pew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
