apiVersion: v1
kind: Secret
metadata:
    name: leaderboard-db-secret
    namespace: leaderboard
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9MFqyuNBrpcJMoI=,iv:lrKaVVlHNlcF2TLGGbXGh2pwH7nFgyGbdvHNYpQk+Cw=,tag:cvgRAPMUYze7hHawivF2sw==,type:str]
    password: ENC[AES256_GCM,data:bCBwguF6hH7a/k4owTFgZ18YVqtXJagDr2dpa0DTMvuM71fk83HuILT1nqSZPNJX,iv:vRFAVCOlRvNfNT0rkwP7cDwn4QDkyLzgWDIbkRLv/Fs=,tag:DKNDm2bDbi29/xgqSFu4qQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaHkwWkx4M3E1b3d0RjIx
            K2YwY3p4RmxEZTBYK1JkWmdPeHgrWkJXcVVjCk8weFp0TkNDa0ozVHQ0dVAwTkxw
            QXhvWjVoKzVkQkpiSlBnOEhoSU80SFUKLS0tIG0vTUxTNG5LSjJqOFlROU1kK1hy
            TXpLVXl6cGYrYkYwRG9GSVM4STFJQTQKdSOgjqg8Id6TmXq8wp1rwoLozBJjAPzH
            hSapYBgiut/UMgNMXHFQ2F327TFSg/5b4eUjq7NrtOmZWWW4ieRx4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T19:58:54Z"
    mac: ENC[AES256_GCM,data:te/y7PRWzPOWdECUbgu1zNX1y8zft8sTnFiaCJI6/sd62o69QkRr7rfJdTswa5KGYSQ+wAdfd9ISmuRS2w2j7i1h92ffOedrV51SCnOtLFDpYyu6AUYxhQ6CrfwSumRXLdRVJoUrxhuvogq72UbfbyswR07Zy2NVU7JJgy+Jn0c=,iv:qVRcYwkOqh9MaFrXXzRcRM7gZSM4faOHMgDXy+NUnIQ=,tag:ID6QAy3hOxNaYxBUVVUGDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
