---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - website/ks.yaml
  - pappwiki/ks.yaml
  - torrent/ks.yaml
  - tuwunel/ks.yaml
  - nextcloud/ks.yaml
  - vaultwarden/ks.yaml
  - jellyfin/ks.yaml
  - authentik/ks.yaml
  - immich/ks.yaml
  - open-webui/ks.yaml
  - payments/ks.yaml
