---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-cluster
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/infra/ceph-cluster
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-releases
  timeout: 10m0s
  wait: true
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
