---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: object-store
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infra/object-store
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ceph-cluster
