apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrent
metadata:
  name: torrent
resources:
  - torrent-config.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - sonarr-config.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - sonarr-httproute.yaml
  - radarr-config.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
  - radarr-httproute.yaml
  - prowlarr-config.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - prowlarr-httproute.yaml
