apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrent
metadata:
  name: torrent
resources:
  - torrent-config.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - arr-config.yaml
  - arr-deployment.yaml
  - arr-service.yaml
  - arr-httproute.yaml
