---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-x3-block-store
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
