---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sonarr
  namespace: torrent
spec:
  interval: 1h
  url: oci://ghcr.io/bjw-s-labs/charts/sonarr
  ref:
    semver: ">=1.0.0"
