apiVersion: v1
kind: ConfigMap
metadata:
  name: website-caddyfile
  namespace: apps
data:
  Caddyfile: |
    :80 {
        route {
            @slash path_regexp slash ^(.*)/+$
            rewrite @slash /my-bucket{re.slash.1}/index.html

            @noext {
                not path *.*
            }
            rewrite @noext /my-bucket{path}/index.html

            rewrite * /my-bucket{uri}

            reverse_proxy http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local
        }
    }
