{
	"apiVersion": "ENC[AES256_GCM,data:Vac=,iv:thOjaVSbkXhC1sZtgIl7S0rKgjKVWAKBgEu5tYzk9v4=,tag:ChUxL63KQMdaXBUYgNHTzg==,type:str]",
	"clusters": [
		{
			"cluster": {
				"certificate-authority-data": "ENC[AES256_GCM,data:ZN7H2ArFXUiwHn2ZxWzvVuFajU3bnhvPYsuCDB+btY+KKSiVARhE3rpCoBn+FmuoHJFvEyKHcFT2bGUQCd6k+eiTdlxetoinVqLgwn/j/f5GsZXujzNM9bLUsWYXvzclvNgzueeC1IBro1WXSFThzqR+ln1AQ1jsqNew0Eb9eZGDyPzyg+4/DV73w3IA+bgqPaPac5jowg6BO9iHE+ObaQF/wGhUEvwDbaSVvVCygQ4VOSaR0mZ7ytlu5c2nFWl/+a5d1wbpAAvh7scHl9QS/i3Aut2lLTa67c4CYDxGk1QLMATGOFHTWEtGHTVrfyOWOqgVNnwQjjYdw8qqeq3fyru89t3SL5EbV4d7U9Ic8ehDD2uIJx8XEz0cDwiZs/QxwODlNFNY79+nKetSAel4vIhpycyd+1zbk0qck6hCBMX3Gi7wCN9qOWx8a/J+ltFBUwuZaQw6mWhkv493NId+lrHbHe/KaUtz4PXTq4E2SGm9U/zLCTcyvL95O9ixE+nxzJSUn6Yf3UtZOB3ztREykwk2838bTHLU9fJ0BbQaKsJmctE4LDpEwEU56EIbecjUlZCUZwZcbaKZXLEEsAENuOCbj9ZrfSGDp9exBr+6ZrOt0rKA/I0KPYN0Q8rSDbBbnAMIvvHxQ9fNrWPL9kBQuT2uPtYaOyuLXCDicvoPdjluTZ6XZF2acMNQe5kc/2TE+9Y31EV6InBYU3QZAFkZyKPBjIcrYTG2IC6vuqnN7QEw3c/9fG19anaLiZOYXBxpS9/DR4nkWCAqQMnH0u1RGRo9JUizMor9e8RI6YcWvnHxAbNxYDg93CdV82GTS6RwuIe5NJCjqczYaQ7DeltNvurB0sxkelW6ORyvQGC70Ei3mLhwCb/xk0eMh/rRmZqGplxxUoBfCvmhEAyPB3Rn9eolpIkNWG6oNEmREGT7cFeuP988CI9LMBgv2sbrcs2TiwObRbMR0Mp99n76AxTqTudHiYZKN88DxaUwuWV8VAk/AVBYk81E5YbflXiVAJbnDYc7FJ4svpMNUSnMdDzpF5PcVDH8I8DtHP3Zng==,iv:z2VSfotBzDohJLZ7uNMKrynSI4bQyfELBWXjMJIuphg=,tag:3jl7d5dXIKcy3mNUlb/Dvg==,type:str]",
				"server": "ENC[AES256_GCM,data:zO2sDaKkfEQ4b3Sb2cKLjb2Xz/LsmMDQVJM=,iv:v3TcxU3k6rQlLe/LY5LvqDgfsh6IplYWVKEXxpPAFH8=,tag:jXMZ2Hsufdol/6j0gn/2pg==,type:str]"
			},
			"name": "ENC[AES256_GCM,data:UcaHq8SuMB8=,iv:/7M/8Dhbxj+/pZZt0SP1dqWs3CefdmR7cOcHEUldSLg=,tag:21UTg30KXkBY5q3+ASZrPg==,type:str]"
		}
	],
	"contexts": [
		{
			"context": {
				"cluster": "ENC[AES256_GCM,data:lxn5t/Nnf5I=,iv:0Uu5ulO/c0zFQltIpjuD1oDza4LPG2Xd86TbSI3eFw4=,tag:L59g9EM0bV3pNO0taF7REQ==,type:str]",
				"namespace": "ENC[AES256_GCM,data:kaYZ+4gUow==,iv:EqfuEOVxwdNLwqtabEBm84L+VhhwXA44aLbJhZjnqPM=,tag:vvDRKcQfaXu7hQmGvurWyA==,type:str]",
				"user": "ENC[AES256_GCM,data:nxNto2H0POfiANqR0OA=,iv:QRBxWsxiYkxlpVxe7roQo5tO7IeXAb+o/+wiom460J4=,tag:3fzQ/t+uDH+KrXDcVlv8Aw==,type:str]"
			},
			"name": "ENC[AES256_GCM,data:FedRDik0lXfKqWvQ5z4=,iv:3Kqfzqmy19GYuPElXaMrWsRgORO8QCHMm7jXuhpLYUk=,tag:apZfQY1PsWmR4tRKbAjMzg==,type:str]"
		}
	],
	"current-context": "ENC[AES256_GCM,data:JFUWYvjS39zVpH9uvJQ=,iv:jH0pGiQ/ltMXxmZ9fjcQsPUrkohZGqG1TKhi0yjZZAY=,tag:WLi8O7YPkjWoLGN9pTP70Q==,type:str]",
	"kind": "ENC[AES256_GCM,data:M9KwqfQ1,iv:mgh1Aj7UtM8OpHHTF7YeEmiUf27QEenypRca0JmG3hs=,tag:73he2eNCs2l19Z8evQKJ4A==,type:str]",
	"users": [
		{
			"name": "ENC[AES256_GCM,data:QCYYkQlBWrC+m51wZV4=,iv:WOhsD18VNr6YjXBlKBAelpX/aucqjBiIwZE69aoIht4=,tag:VW4ykkFje/AzUiJ8BH2O6A==,type:str]",
			"user": {
				"client-certificate-data": "ENC[AES256_GCM,data:q3AUcjBjOTOvmV7DpmM+abaXhwdUHfNDXBDfT+NFiIOaDQ4iCU4g7h8e2sWQ1GzIYUGGp0xCdQaQ0yIgpI5Lg8ytwVITiSg3gC1DG9C8fMyfQ+8FrRH8ap3e32YUAYSVoWgZQMlc/Z4sbJm7S/uCt4Ou9z4ovvxDd2jUyDDeJ6q+9HuQ01omh2k32aaL+vG11CHwzLbFNd6x4yeOKX5GekoWss87jJqJuFG/bSFhBJ7Q7CZtXRcBf51BkREq9Rrt5rgw1WOy07uuvljW5fwQ1r7d3waVBx1p7qUsT2/hYGaiKu3RLiFrqtndQHmVgZhf3p1qbL7C2GYeCLn0GrUx3IXM0/leELiJPLHy65fP8PAJMrIZpANqrZ8QAEJ5L3qGxOoa/SsmuG7imVpstU6+HaDDWIBop1Zr/61utNJRJ8WkPMs1XbSty8Te7LJK1MZOip9W0Ghze39x07juZ9DHR/hGtn0aAdLqOlCSd+4JzxPTKruz4lA1ZbSXoJ/YtFYuowUa+sA8xSWJQXa1WZKIwP0Aq6A3VLPBUdSGpztyFC1QK/KoGe8yGHt7BcuxoG4gdDqkm4DWFLsq8LhRxrCnyc9JEwB4K44Oj5ap5PFI3K1xUkK/CGcWRrPuU0Y6uZbLBAJfG0Ffc9GPV2L2JYSDC9y6ZLQyJ46gdADSdq7weISg5kjoD2N3u0RiRU7+o1KOnCQTa6LxsU+9YLFYMNcWXlGRluCZ4rnKJI3yu5E5G+D1lT5MoGttNYaC9Qt+zcHN4EikDmcgTtgmJAiiX5vHG0Ve8EJewHsXRVUCqx9y5Pt1a3W5EOL1Df/aerWaLHNHpP1Ur5mFWPfNU5wt4xN9rNcyKxJv1d3EeTOulRdx3Q34hVTZAAdZ86ofiNbHH8ceDmZAz4p2VyHYObZadLkA8/6eXK03OpxplLm6TeKhnkOWxQ/gWK5Bt1Em/kJ1Gc9Akg+8NKzmMQlOEmXI1dl2Sz3y9oydyR0mYGkWubv69TrgOOvRrRwUwYjRQrLZESepVv9sr3jP3mHSe/fDyJlFfA==,iv:JyXtEv+jkqsYRE/PZN44M7aWGw0HHEcpGKXqrY85QEg=,tag:+cpDOzAtjQfO1bYXX87Umg==,type:str]",
				"client-key-data": "ENC[AES256_GCM,data:uovBWcN4SnMi71dSJGvG87U+5CKycv/oyV21xu+QlhNQA+66vJtGIUm/vmTtePQ6VAw9SgtaeXX+QGpnAMqDVEASCr7lnb42yNYpuJAGQXMrWsb6Sqx+V3AQ1uiGOaieDppkX2Ur/MZUVpPrmFj6uIhYjPCr8AnBVScMkB5MaGer198iLtB7a3hc0AyVKIDII99uA/+Y/RuglUF4z9c+T9gNsokPkUzZ3dtufRLe2f7zB/1NJuKzsxDZYZWUaazG1OtG8o7jVzfj/YC3seT3fAlWqgHq6pQ2wot1JWCDxEUTeY1V0dXfvOQTWM4myY4Hz6rLq8j3YMAsB2KmfyzuIKy7F+0Eenn1xxjadS38S5pV2u+TorXTjIJXZ7ju5dlpyL1E1On1zufZHy3RdvjMHQ==,iv:OBsCbmcjkeBv8KZANpsZRH4UEdY9DvbTm2mDS9SSOiY=,tag:DjVmjvDRhBjJ7E+nhHEuFQ==,type:str]"
			}
		}
	],
	"sops": {
		"age": [
			{
				"recipient": "age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNktyZ3VsRmh2TzJxSFlR\nRE5NWWdnU1FTUnBWWTM2V2NrZC9JVm42WkMwCjE4UkNqUmNzZXp0TU1XRnM5aFl3\nZCtmays0QWQ4Y1VXNXJieTk4THJpWGMKLS0tIDBsRE9WNys4ZUU2TEdZYzFiOTRx\naUlZOG92NllwenpESmtUU0dELzJUQ28KbvoX9gukkYBdLTi4roBU63CrIdmTsyC3\nTeMY6Ep9LxK706V5P4p8sw9hpFjT5WiP7VLlIcUnQ3XGW3G0cR/kTg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-29T05:21:38Z",
		"mac": "ENC[AES256_GCM,data:Dl/ZF40ftK1SXJ7JfiwT7Z+qNQBu8I3Rc93QanzTVz1QiiHGf6H1qJ1ucF5HtdPYGRCHQKdWwTMKuuZB5mqOSnlDbcqeUYlQ2aCbhhhkxOX1Rcuyn7wEokaPF4u4Znai5t5u2SLBuOrC6rTBGum/Y8avgjn/Zv0K5dXcA+N93kY=,iv:sbtDXnams7Spf5tJehafZNSHTIdnFiYAf2/yGI4gIu4=,tag:d0PFsRVJ44HDSUhI5COQGg==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.12.1"
	}
}
