apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:3xzoX+KPZkgW,iv:PdqYSXmSxhkjBiqyW9zaw6285tA7TBtQDNqYv5Jgf/0=,tag:1YrJfiE6kp19EjwFB535Mg==,type:str]
    password: ENC[AES256_GCM,data:E8VJJk/R+Nogj9tI8OiUv7HaOQTcr/ixnE662FO6kevn1hwbRHSiINDh+aq1yWsobH4=,iv:g40lw9mdAdOo4JqwV5kjH8BsH0ab6+87mDuzGze23n4=,tag:yhOPTmV9TrqvJsi6aS65zQ==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdndPbENCMW5aOE1TdnVY
            ZjVNQzlOYTR6eDVvaXBYRmZ0Y2pBU3cwNVNjCkNCVjJCdWhWSjFONTJBbjFCRW1Y
            c0E5N1RpOW8yQVBXaThrTTRsQzRRVmcKLS0tIEdnUFJWdmhTMTB0ck9jbVFSY1dO
            bitxcURMQllpVWp2bUVBVStOM1I1RTgKPQYAk1x/N8jtyKygLstsbskER6hrDUIQ
            D340XYmn9j6i4mlfJREdeO7YRD0OPXXnv1ZRdS7RnnvcKHHCdkwRcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T04:21:24Z"
    mac: ENC[AES256_GCM,data:vVI6ZBLxz4cCYO2OVT09/ZCCm1aonOmSaunkY1VE0YsiMZ2s2fr656Eo+PgsIg9M2wlzJRy3bPnrnz3fAbEoN/83Quh48ZLrHtGOOwo4tbg42Q6nABCxQbblD9+NuvDwtCqBGIwhovKgOOT4S1pBh/jwzGd/kBbUnPWBklwPQss=,iv:wL/vt9TDWnp9hov2ncCe9lA6IS0KdwNC4FdnPpCxnGQ=,tag:jGCKpnvEoUBkRlBN0Lvnug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
